/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeyCreateRequest,
  ApiKeyCreateResponse,
  ApiKeyDetailResponse,
  ApiKeyListResponse,
  ApiKeyPatchRequest,
  ApiKeyRevokeResponse,
  ApiKeyRotateResponse,
  HTTPValidationError,
} from '../models/index';
import {
    ApiKeyCreateRequestFromJSON,
    ApiKeyCreateRequestToJSON,
    ApiKeyCreateResponseFromJSON,
    ApiKeyCreateResponseToJSON,
    ApiKeyDetailResponseFromJSON,
    ApiKeyDetailResponseToJSON,
    ApiKeyListResponseFromJSON,
    ApiKeyListResponseToJSON,
    ApiKeyPatchRequestFromJSON,
    ApiKeyPatchRequestToJSON,
    ApiKeyRevokeResponseFromJSON,
    ApiKeyRevokeResponseToJSON,
    ApiKeyRotateResponseFromJSON,
    ApiKeyRotateResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface CreateApiKeyApiV1ApiKeysPostRequest {
    apiKeyCreateRequest: ApiKeyCreateRequest;
}

export interface GetApiKeyApiV1ApiKeysApiKeyIdGetRequest {
    apiKeyId: string;
}

export interface PatchApiKeyApiV1ApiKeysApiKeyIdPatchRequest {
    apiKeyId: string;
    apiKeyPatchRequest: ApiKeyPatchRequest;
}

export interface RevokeApiKeyApiV1ApiKeysApiKeyIdDeleteRequest {
    apiKeyId: string;
}

export interface RotateApiKeyApiV1ApiKeysApiKeyIdRotatePostRequest {
    apiKeyId: string;
}

/**
 * 
 */
export class ApiKeysApi extends runtime.BaseAPI {

    /**
     * Create Api Key
     */
    async createApiKeyApiV1ApiKeysPostRaw(requestParameters: CreateApiKeyApiV1ApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyCreateResponse>> {
        if (requestParameters['apiKeyCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'apiKeyCreateRequest',
                'Required parameter "apiKeyCreateRequest" was null or undefined when calling createApiKeyApiV1ApiKeysPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyCreateRequestToJSON(requestParameters['apiKeyCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create Api Key
     */
    async createApiKeyApiV1ApiKeysPost(requestParameters: CreateApiKeyApiV1ApiKeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyCreateResponse> {
        const response = await this.createApiKeyApiV1ApiKeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Api Key
     */
    async getApiKeyApiV1ApiKeysApiKeyIdGetRaw(requestParameters: GetApiKeyApiV1ApiKeysApiKeyIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyDetailResponse>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling getApiKeyApiV1ApiKeysApiKeyIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys/{api_key_id}`.replace(`{${"api_key_id"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get Api Key
     */
    async getApiKeyApiV1ApiKeysApiKeyIdGet(requestParameters: GetApiKeyApiV1ApiKeysApiKeyIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyDetailResponse> {
        const response = await this.getApiKeyApiV1ApiKeysApiKeyIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Api Keys
     */
    async listApiKeysApiV1ApiKeysGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyListResponseFromJSON(jsonValue));
    }

    /**
     * List Api Keys
     */
    async listApiKeysApiV1ApiKeysGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyListResponse> {
        const response = await this.listApiKeysApiV1ApiKeysGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Patch Api Key
     */
    async patchApiKeyApiV1ApiKeysApiKeyIdPatchRaw(requestParameters: PatchApiKeyApiV1ApiKeysApiKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyDetailResponse>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling patchApiKeyApiV1ApiKeysApiKeyIdPatch().'
            );
        }

        if (requestParameters['apiKeyPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'apiKeyPatchRequest',
                'Required parameter "apiKeyPatchRequest" was null or undefined when calling patchApiKeyApiV1ApiKeysApiKeyIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys/{api_key_id}`.replace(`{${"api_key_id"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyPatchRequestToJSON(requestParameters['apiKeyPatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyDetailResponseFromJSON(jsonValue));
    }

    /**
     * Patch Api Key
     */
    async patchApiKeyApiV1ApiKeysApiKeyIdPatch(requestParameters: PatchApiKeyApiV1ApiKeysApiKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyDetailResponse> {
        const response = await this.patchApiKeyApiV1ApiKeysApiKeyIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke Api Key
     */
    async revokeApiKeyApiV1ApiKeysApiKeyIdDeleteRaw(requestParameters: RevokeApiKeyApiV1ApiKeysApiKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyRevokeResponse>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling revokeApiKeyApiV1ApiKeysApiKeyIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys/{api_key_id}`.replace(`{${"api_key_id"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyRevokeResponseFromJSON(jsonValue));
    }

    /**
     * Revoke Api Key
     */
    async revokeApiKeyApiV1ApiKeysApiKeyIdDelete(requestParameters: RevokeApiKeyApiV1ApiKeysApiKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyRevokeResponse> {
        const response = await this.revokeApiKeyApiV1ApiKeysApiKeyIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke the existing key and create a new one with the same name.
     * Rotate Api Key
     */
    async rotateApiKeyApiV1ApiKeysApiKeyIdRotatePostRaw(requestParameters: RotateApiKeyApiV1ApiKeysApiKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyRotateResponse>> {
        if (requestParameters['apiKeyId'] == null) {
            throw new runtime.RequiredError(
                'apiKeyId',
                'Required parameter "apiKeyId" was null or undefined when calling rotateApiKeyApiV1ApiKeysApiKeyIdRotatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/api-keys/{api_key_id}/rotate`.replace(`{${"api_key_id"}}`, encodeURIComponent(String(requestParameters['apiKeyId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyRotateResponseFromJSON(jsonValue));
    }

    /**
     * Revoke the existing key and create a new one with the same name.
     * Rotate Api Key
     */
    async rotateApiKeyApiV1ApiKeysApiKeyIdRotatePost(requestParameters: RotateApiKeyApiV1ApiKeysApiKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyRotateResponse> {
        const response = await this.rotateApiKeyApiV1ApiKeysApiKeyIdRotatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
