/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  BatchCreateRequest,
  BatchItemsListResponse,
  BatchResponse,
  BatchesListResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    BatchCreateRequestFromJSON,
    BatchCreateRequestToJSON,
    BatchItemsListResponseFromJSON,
    BatchItemsListResponseToJSON,
    BatchResponseFromJSON,
    BatchResponseToJSON,
    BatchesListResponseFromJSON,
    BatchesListResponseToJSON,
} from '../models/index';

export interface CancelBatchRequest {
    batchId: string;
}

export interface CreateBatchRequest {
    batchCreateRequest: BatchCreateRequest;
}

export interface DownloadBatchRequest {
    batchId: string;
}

export interface GetBatchRequest {
    batchId: string;
}

export interface ListBatchItemsRequest {
    batchId: string;
    limit?: number;
    cursor?: string | null;
}

export interface ListBatchesRequest {
    limit?: number;
    cursor?: string | null;
}

/**
 * 
 */
export class BatchesApi extends runtime.BaseAPI {

    /**
     * Cancel Batch
     */
    async cancelBatchRaw(requestParameters: CancelBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchResponse>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling cancelBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches/{batch_id}/cancel`.replace(`{${"batch_id"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Batch
     */
    async cancelBatch(requestParameters: CancelBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchResponse> {
        const response = await this.cancelBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Batch
     */
    async createBatchRaw(requestParameters: CreateBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchResponse>> {
        if (requestParameters['batchCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'batchCreateRequest',
                'Required parameter "batchCreateRequest" was null or undefined when calling createBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BatchCreateRequestToJSON(requestParameters['batchCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchResponseFromJSON(jsonValue));
    }

    /**
     * Create Batch
     */
    async createBatch(requestParameters: CreateBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchResponse> {
        const response = await this.createBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download Batch
     */
    async downloadBatchRaw(requestParameters: DownloadBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling downloadBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches/{batch_id}/download`.replace(`{${"batch_id"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Download Batch
     */
    async downloadBatch(requestParameters: DownloadBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Batch
     */
    async getBatchRaw(requestParameters: GetBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchResponse>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling getBatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches/{batch_id}`.replace(`{${"batch_id"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchResponseFromJSON(jsonValue));
    }

    /**
     * Get Batch
     */
    async getBatch(requestParameters: GetBatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchResponse> {
        const response = await this.getBatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Batch Items
     */
    async listBatchItemsRaw(requestParameters: ListBatchItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchItemsListResponse>> {
        if (requestParameters['batchId'] == null) {
            throw new runtime.RequiredError(
                'batchId',
                'Required parameter "batchId" was null or undefined when calling listBatchItems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches/{batch_id}/items`.replace(`{${"batch_id"}}`, encodeURIComponent(String(requestParameters['batchId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchItemsListResponseFromJSON(jsonValue));
    }

    /**
     * List Batch Items
     */
    async listBatchItems(requestParameters: ListBatchItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchItemsListResponse> {
        const response = await this.listBatchItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Batches
     */
    async listBatchesRaw(requestParameters: ListBatchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BatchesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/batches`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BatchesListResponseFromJSON(jsonValue));
    }

    /**
     * List Batches
     */
    async listBatches(requestParameters: ListBatchesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BatchesListResponse> {
        const response = await this.listBatchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
