/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  BrandingProfileCreateRequest,
  BrandingProfilePatchRequest,
  BrandingProfileResponse,
  BrandingProfilesListResponse,
  SimpleBoolResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    BrandingProfileCreateRequestFromJSON,
    BrandingProfileCreateRequestToJSON,
    BrandingProfilePatchRequestFromJSON,
    BrandingProfilePatchRequestToJSON,
    BrandingProfileResponseFromJSON,
    BrandingProfileResponseToJSON,
    BrandingProfilesListResponseFromJSON,
    BrandingProfilesListResponseToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
} from '../models/index';

export interface CreateBrandingProfileRequest {
    brandingProfileCreateRequest: BrandingProfileCreateRequest;
}

export interface DeleteBrandingLogoRequest {
    profileId: string;
}

export interface DeleteBrandingProfileRequest {
    profileId: string;
}

export interface GetBrandingProfileRequest {
    profileId: string;
}

export interface SetDefaultBrandingProfileRequest {
    profileId: string;
}

export interface UpdateBrandingProfileRequest {
    profileId: string;
    brandingProfilePatchRequest: BrandingProfilePatchRequest;
}

export interface UploadBrandingLogoRequest {
    profileId: string;
    file: Blob;
}

/**
 * 
 */
export class BrandingProfilesApi extends runtime.BaseAPI {

    /**
     * Create a look: colours, logo, fonts and footer.  Applies on top of whichever template a render names, so one template can serve several brands. Mark one as the default and documents that name no profile will use it.
     * Create Branding Profile
     */
    async createBrandingProfileRaw(requestParameters: CreateBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['brandingProfileCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'brandingProfileCreateRequest',
                'Required parameter "brandingProfileCreateRequest" was null or undefined when calling createBrandingProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BrandingProfileCreateRequestToJSON(requestParameters['brandingProfileCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Create a look: colours, logo, fonts and footer.  Applies on top of whichever template a render names, so one template can serve several brands. Mark one as the default and documents that name no profile will use it.
     * Create Branding Profile
     */
    async createBrandingProfile(requestParameters: CreateBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.createBrandingProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove this profile\'s logo, leaving its colours and text intact.
     * Delete Branding Logo
     */
    async deleteBrandingLogoRaw(requestParameters: DeleteBrandingLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling deleteBrandingLogo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/logo`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Remove this profile\'s logo, leaving its colours and text intact.
     * Delete Branding Logo
     */
    async deleteBrandingLogo(requestParameters: DeleteBrandingLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteBrandingLogoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Remove a branding profile.  Deleting the default is allowed: the oldest remaining profile becomes the default in its place, so documents that name no profile keep rendering.
     * Delete Branding Profile
     */
    async deleteBrandingProfileRaw(requestParameters: DeleteBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling deleteBrandingProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Remove a branding profile.  Deleting the default is allowed: the oldest remaining profile becomes the default in its place, so documents that name no profile keep rendering.
     * Delete Branding Profile
     */
    async deleteBrandingProfile(requestParameters: DeleteBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteBrandingProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * One branding profile.
     * Get Branding Profile
     */
    async getBrandingProfileRaw(requestParameters: GetBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling getBrandingProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * One branding profile.
     * Get Branding Profile
     */
    async getBrandingProfile(requestParameters: GetBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.getBrandingProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * The looks a document can be rendered in, newest first.  Colours, logo, fonts and footer text — how a document appears. Who it is issued by is a business profile, which is a different thing.
     * List Branding Profiles
     */
    async listBrandingProfilesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfilesListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfilesListResponseFromJSON(jsonValue));
    }

    /**
     * The looks a document can be rendered in, newest first.  Colours, logo, fonts and footer text — how a document appears. Who it is issued by is a business profile, which is a different thing.
     * List Branding Profiles
     */
    async listBrandingProfiles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfilesListResponse> {
        const response = await this.listBrandingProfilesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Make this the profile used when a document names none.  Exactly one profile is the default; setting a new one clears the previous.
     * Set Default Branding Profile
     */
    async setDefaultBrandingProfileRaw(requestParameters: SetDefaultBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling setDefaultBrandingProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/default`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Make this the profile used when a document names none.  Exactly one profile is the default; setting a new one clears the previous.
     * Set Default Branding Profile
     */
    async setDefaultBrandingProfile(requestParameters: SetDefaultBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.setDefaultBrandingProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Change a branding profile.  Only the fields you send are changed. `hide_invoicepdfs_branding` is stored on any plan but only honoured on a plan that includes it — it is applied when a document renders, not validated here, so setting it on a plan without it is accepted and has no effect.
     * Update Branding Profile
     */
    async updateBrandingProfileRaw(requestParameters: UpdateBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateBrandingProfile().'
            );
        }

        if (requestParameters['brandingProfilePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'brandingProfilePatchRequest',
                'Required parameter "brandingProfilePatchRequest" was null or undefined when calling updateBrandingProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BrandingProfilePatchRequestToJSON(requestParameters['brandingProfilePatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Change a branding profile.  Only the fields you send are changed. `hide_invoicepdfs_branding` is stored on any plan but only honoured on a plan that includes it — it is applied when a document renders, not validated here, so setting it on a plan without it is accepted and has no effect.
     * Update Branding Profile
     */
    async updateBrandingProfile(requestParameters: UpdateBrandingProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.updateBrandingProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Attach a logo image to this branding profile.  Replaces whatever logo the profile carried. The image is embedded when a document renders, so a later change applies to future renders and leaves PDFs already produced as they were.
     * Upload Branding Logo
     */
    async uploadBrandingLogoRaw(requestParameters: UploadBrandingLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling uploadBrandingLogo().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadBrandingLogo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/logo`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Attach a logo image to this branding profile.  Replaces whatever logo the profile carried. The image is embedded when a document renders, so a later change applies to future renders and leaves PDFs already produced as they were.
     * Upload Branding Logo
     */
    async uploadBrandingLogo(requestParameters: UploadBrandingLogoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.uploadBrandingLogoRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
