/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BrandingProfileCreateRequest,
  BrandingProfilePatchRequest,
  BrandingProfileResponse,
  BrandingProfilesListResponse,
  HTTPValidationError,
  SimpleBoolResponse,
} from '../models/index';
import {
    BrandingProfileCreateRequestFromJSON,
    BrandingProfileCreateRequestToJSON,
    BrandingProfilePatchRequestFromJSON,
    BrandingProfilePatchRequestToJSON,
    BrandingProfileResponseFromJSON,
    BrandingProfileResponseToJSON,
    BrandingProfilesListResponseFromJSON,
    BrandingProfilesListResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
} from '../models/index';

export interface CreateProfileApiV1BrandingProfilesPostRequest {
    brandingProfileCreateRequest: BrandingProfileCreateRequest;
}

export interface DeleteLogoApiV1BrandingProfilesProfileIdLogoDeleteRequest {
    profileId: string;
}

export interface DeleteProfileApiV1BrandingProfilesProfileIdDeleteRequest {
    profileId: string;
}

export interface GetProfileApiV1BrandingProfilesProfileIdGetRequest {
    profileId: string;
}

export interface SetDefaultApiV1BrandingProfilesProfileIdDefaultPostRequest {
    profileId: string;
}

export interface UpdateProfileApiV1BrandingProfilesProfileIdPatchRequest {
    profileId: string;
    brandingProfilePatchRequest: BrandingProfilePatchRequest;
}

export interface UploadLogoApiV1BrandingProfilesProfileIdLogoPostRequest {
    profileId: string;
    file: Blob;
}

/**
 * 
 */
export class BrandingProfilesApi extends runtime.BaseAPI {

    /**
     * Create Profile
     */
    async createProfileApiV1BrandingProfilesPostRaw(requestParameters: CreateProfileApiV1BrandingProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['brandingProfileCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'brandingProfileCreateRequest',
                'Required parameter "brandingProfileCreateRequest" was null or undefined when calling createProfileApiV1BrandingProfilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BrandingProfileCreateRequestToJSON(requestParameters['brandingProfileCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Create Profile
     */
    async createProfileApiV1BrandingProfilesPost(requestParameters: CreateProfileApiV1BrandingProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.createProfileApiV1BrandingProfilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Logo
     */
    async deleteLogoApiV1BrandingProfilesProfileIdLogoDeleteRaw(requestParameters: DeleteLogoApiV1BrandingProfilesProfileIdLogoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling deleteLogoApiV1BrandingProfilesProfileIdLogoDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/logo`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Logo
     */
    async deleteLogoApiV1BrandingProfilesProfileIdLogoDelete(requestParameters: DeleteLogoApiV1BrandingProfilesProfileIdLogoDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteLogoApiV1BrandingProfilesProfileIdLogoDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Profile
     */
    async deleteProfileApiV1BrandingProfilesProfileIdDeleteRaw(requestParameters: DeleteProfileApiV1BrandingProfilesProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling deleteProfileApiV1BrandingProfilesProfileIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Profile
     */
    async deleteProfileApiV1BrandingProfilesProfileIdDelete(requestParameters: DeleteProfileApiV1BrandingProfilesProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteProfileApiV1BrandingProfilesProfileIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Profile
     */
    async getProfileApiV1BrandingProfilesProfileIdGetRaw(requestParameters: GetProfileApiV1BrandingProfilesProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling getProfileApiV1BrandingProfilesProfileIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get Profile
     */
    async getProfileApiV1BrandingProfilesProfileIdGet(requestParameters: GetProfileApiV1BrandingProfilesProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.getProfileApiV1BrandingProfilesProfileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Profiles
     */
    async listProfilesApiV1BrandingProfilesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfilesListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfilesListResponseFromJSON(jsonValue));
    }

    /**
     * List Profiles
     */
    async listProfilesApiV1BrandingProfilesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfilesListResponse> {
        const response = await this.listProfilesApiV1BrandingProfilesGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Set Default
     */
    async setDefaultApiV1BrandingProfilesProfileIdDefaultPostRaw(requestParameters: SetDefaultApiV1BrandingProfilesProfileIdDefaultPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling setDefaultApiV1BrandingProfilesProfileIdDefaultPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/default`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Set Default
     */
    async setDefaultApiV1BrandingProfilesProfileIdDefaultPost(requestParameters: SetDefaultApiV1BrandingProfilesProfileIdDefaultPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.setDefaultApiV1BrandingProfilesProfileIdDefaultPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Profile
     */
    async updateProfileApiV1BrandingProfilesProfileIdPatchRaw(requestParameters: UpdateProfileApiV1BrandingProfilesProfileIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling updateProfileApiV1BrandingProfilesProfileIdPatch().'
            );
        }

        if (requestParameters['brandingProfilePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'brandingProfilePatchRequest',
                'Required parameter "brandingProfilePatchRequest" was null or undefined when calling updateProfileApiV1BrandingProfilesProfileIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BrandingProfilePatchRequestToJSON(requestParameters['brandingProfilePatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Update Profile
     */
    async updateProfileApiV1BrandingProfilesProfileIdPatch(requestParameters: UpdateProfileApiV1BrandingProfilesProfileIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.updateProfileApiV1BrandingProfilesProfileIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload Logo
     */
    async uploadLogoApiV1BrandingProfilesProfileIdLogoPostRaw(requestParameters: UploadLogoApiV1BrandingProfilesProfileIdLogoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BrandingProfileResponse>> {
        if (requestParameters['profileId'] == null) {
            throw new runtime.RequiredError(
                'profileId',
                'Required parameter "profileId" was null or undefined when calling uploadLogoApiV1BrandingProfilesProfileIdLogoPost().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadLogoApiV1BrandingProfilesProfileIdLogoPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        const response = await this.request({
            path: `/api/v1/branding-profiles/{profile_id}/logo`.replace(`{${"profile_id"}}`, encodeURIComponent(String(requestParameters['profileId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BrandingProfileResponseFromJSON(jsonValue));
    }

    /**
     * Upload Logo
     */
    async uploadLogoApiV1BrandingProfilesProfileIdLogoPost(requestParameters: UploadLogoApiV1BrandingProfilesProfileIdLogoPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BrandingProfileResponse> {
        const response = await this.uploadLogoApiV1BrandingProfilesProfileIdLogoPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
