/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BusinessProfileCreate,
  BusinessProfilePatch,
  BusinessProfileResponse,
  BusinessProfilesListResponse,
  HTTPValidationError,
  SimpleBoolResponse,
} from '../models/index';
import {
    BusinessProfileCreateFromJSON,
    BusinessProfileCreateToJSON,
    BusinessProfilePatchFromJSON,
    BusinessProfilePatchToJSON,
    BusinessProfileResponseFromJSON,
    BusinessProfileResponseToJSON,
    BusinessProfilesListResponseFromJSON,
    BusinessProfilesListResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
} from '../models/index';

export interface CreateBusinessProfileApiV1BusinessProfilesPostRequest {
    businessProfileCreate: BusinessProfileCreate;
    idempotencyKey?: string | null;
}

export interface DeleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDeleteRequest {
    businessProfileId: string;
}

export interface GetBusinessProfileApiV1BusinessProfilesBusinessProfileIdGetRequest {
    businessProfileId: string;
}

export interface ListBusinessProfilesApiV1BusinessProfilesGetRequest {
    limit?: number;
    cursor?: string | null;
}

export interface PatchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatchRequest {
    businessProfileId: string;
    businessProfilePatch: BusinessProfilePatch;
    idempotencyKey?: string | null;
}

/**
 * 
 */
export class BusinessProfilesApi extends runtime.BaseAPI {

    /**
     * Create Business Profile
     */
    async createBusinessProfileApiV1BusinessProfilesPostRaw(requestParameters: CreateBusinessProfileApiV1BusinessProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessProfileResponse>> {
        if (requestParameters['businessProfileCreate'] == null) {
            throw new runtime.RequiredError(
                'businessProfileCreate',
                'Required parameter "businessProfileCreate" was null or undefined when calling createBusinessProfileApiV1BusinessProfilesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/business-profiles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BusinessProfileCreateToJSON(requestParameters['businessProfileCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessProfileResponseFromJSON(jsonValue));
    }

    /**
     * Create Business Profile
     */
    async createBusinessProfileApiV1BusinessProfilesPost(requestParameters: CreateBusinessProfileApiV1BusinessProfilesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessProfileResponse> {
        const response = await this.createBusinessProfileApiV1BusinessProfilesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Business Profile
     */
    async deleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDeleteRaw(requestParameters: DeleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['businessProfileId'] == null) {
            throw new runtime.RequiredError(
                'businessProfileId',
                'Required parameter "businessProfileId" was null or undefined when calling deleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/business-profiles/{business_profile_id}`.replace(`{${"business_profile_id"}}`, encodeURIComponent(String(requestParameters['businessProfileId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Business Profile
     */
    async deleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDelete(requestParameters: DeleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteBusinessProfileApiV1BusinessProfilesBusinessProfileIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Business Profile
     */
    async getBusinessProfileApiV1BusinessProfilesBusinessProfileIdGetRaw(requestParameters: GetBusinessProfileApiV1BusinessProfilesBusinessProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessProfileResponse>> {
        if (requestParameters['businessProfileId'] == null) {
            throw new runtime.RequiredError(
                'businessProfileId',
                'Required parameter "businessProfileId" was null or undefined when calling getBusinessProfileApiV1BusinessProfilesBusinessProfileIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/business-profiles/{business_profile_id}`.replace(`{${"business_profile_id"}}`, encodeURIComponent(String(requestParameters['businessProfileId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessProfileResponseFromJSON(jsonValue));
    }

    /**
     * Get Business Profile
     */
    async getBusinessProfileApiV1BusinessProfilesBusinessProfileIdGet(requestParameters: GetBusinessProfileApiV1BusinessProfilesBusinessProfileIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessProfileResponse> {
        const response = await this.getBusinessProfileApiV1BusinessProfilesBusinessProfileIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Business Profiles
     */
    async listBusinessProfilesApiV1BusinessProfilesGetRaw(requestParameters: ListBusinessProfilesApiV1BusinessProfilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessProfilesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/business-profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessProfilesListResponseFromJSON(jsonValue));
    }

    /**
     * List Business Profiles
     */
    async listBusinessProfilesApiV1BusinessProfilesGet(requestParameters: ListBusinessProfilesApiV1BusinessProfilesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessProfilesListResponse> {
        const response = await this.listBusinessProfilesApiV1BusinessProfilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Patch Business Profile
     */
    async patchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatchRaw(requestParameters: PatchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BusinessProfileResponse>> {
        if (requestParameters['businessProfileId'] == null) {
            throw new runtime.RequiredError(
                'businessProfileId',
                'Required parameter "businessProfileId" was null or undefined when calling patchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatch().'
            );
        }

        if (requestParameters['businessProfilePatch'] == null) {
            throw new runtime.RequiredError(
                'businessProfilePatch',
                'Required parameter "businessProfilePatch" was null or undefined when calling patchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/business-profiles/{business_profile_id}`.replace(`{${"business_profile_id"}}`, encodeURIComponent(String(requestParameters['businessProfileId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BusinessProfilePatchToJSON(requestParameters['businessProfilePatch']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BusinessProfileResponseFromJSON(jsonValue));
    }

    /**
     * Patch Business Profile
     */
    async patchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatch(requestParameters: PatchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BusinessProfileResponse> {
        const response = await this.patchBusinessProfileApiV1BusinessProfilesBusinessProfileIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
