/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  InvoiceAttachmentCreateRequest,
  InvoiceAttachmentResponse,
  InvoiceAttachmentsListResponse,
  SimpleBoolResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    InvoiceAttachmentCreateRequestFromJSON,
    InvoiceAttachmentCreateRequestToJSON,
    InvoiceAttachmentResponseFromJSON,
    InvoiceAttachmentResponseToJSON,
    InvoiceAttachmentsListResponseFromJSON,
    InvoiceAttachmentsListResponseToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
} from '../models/index';

export interface CreateDocumentAttachmentRequest {
    documentId: string;
    invoiceAttachmentCreateRequest: InvoiceAttachmentCreateRequest;
}

export interface DeleteDocumentAttachmentRequest {
    documentId: string;
    attachmentId: string;
}

export interface ListDocumentAttachmentsRequest {
    documentId: string;
}

/**
 * 
 */
export class DocumentAttachmentsApi extends runtime.BaseAPI {

    /**
     * Create Attachment
     */
    async createDocumentAttachmentRaw(requestParameters: CreateDocumentAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceAttachmentResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling createDocumentAttachment().'
            );
        }

        if (requestParameters['invoiceAttachmentCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'invoiceAttachmentCreateRequest',
                'Required parameter "invoiceAttachmentCreateRequest" was null or undefined when calling createDocumentAttachment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{document_id}/attachments`.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InvoiceAttachmentCreateRequestToJSON(requestParameters['invoiceAttachmentCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceAttachmentResponseFromJSON(jsonValue));
    }

    /**
     * Create Attachment
     */
    async createDocumentAttachment(requestParameters: CreateDocumentAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceAttachmentResponse> {
        const response = await this.createDocumentAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Attachment
     */
    async deleteDocumentAttachmentRaw(requestParameters: DeleteDocumentAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling deleteDocumentAttachment().'
            );
        }

        if (requestParameters['attachmentId'] == null) {
            throw new runtime.RequiredError(
                'attachmentId',
                'Required parameter "attachmentId" was null or undefined when calling deleteDocumentAttachment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{document_id}/attachments/{attachment_id}`.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId']))).replace(`{${"attachment_id"}}`, encodeURIComponent(String(requestParameters['attachmentId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Attachment
     */
    async deleteDocumentAttachment(requestParameters: DeleteDocumentAttachmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteDocumentAttachmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Attachments
     */
    async listDocumentAttachmentsRaw(requestParameters: ListDocumentAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceAttachmentsListResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling listDocumentAttachments().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{document_id}/attachments`.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceAttachmentsListResponseFromJSON(jsonValue));
    }

    /**
     * List Attachments
     */
    async listDocumentAttachments(requestParameters: ListDocumentAttachmentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceAttachmentsListResponse> {
        const response = await this.listDocumentAttachmentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
