/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthResponse,
  ReadyResponse,
  VersionResponse,
} from '../models/index';
import {
    HealthResponseFromJSON,
    HealthResponseToJSON,
    ReadyResponseFromJSON,
    ReadyResponseToJSON,
    VersionResponseFromJSON,
    VersionResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Health
     */
    async healthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Health
     */
    async healthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Ready
     */
    async readyReadyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadyResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ready`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadyResponseFromJSON(jsonValue));
    }

    /**
     * Ready
     */
    async readyReadyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadyResponse> {
        const response = await this.readyReadyGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Version
     */
    async versionVersionGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VersionResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/version`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VersionResponseFromJSON(jsonValue));
    }

    /**
     * Version
     */
    async versionVersionGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VersionResponse> {
        const response = await this.versionVersionGetRaw(initOverrides);
        return await response.value();
    }

}
