/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  ImportCreateRequest,
  ImportResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    ImportCreateRequestFromJSON,
    ImportCreateRequestToJSON,
    ImportResponseFromJSON,
    ImportResponseToJSON,
} from '../models/index';

export interface CancelImportRequest {
    importId: string;
}

export interface ConfirmImportRequest {
    importId: string;
}

export interface CreateImportRequest {
    importCreateRequest: ImportCreateRequest;
}

export interface GetImportRequest {
    importId: string;
}

/**
 * 
 */
export class ImportsApi extends runtime.BaseAPI {

    /**
     * Cancel Import
     */
    async cancelImportRaw(requestParameters: CancelImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling cancelImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}/cancel`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Import
     */
    async cancelImport(requestParameters: CancelImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.cancelImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Confirm Import
     */
    async confirmImportRaw(requestParameters: ConfirmImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling confirmImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}/confirm`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Confirm Import
     */
    async confirmImport(requestParameters: ConfirmImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.confirmImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Import
     */
    async createImportRaw(requestParameters: CreateImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'importCreateRequest',
                'Required parameter "importCreateRequest" was null or undefined when calling createImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportCreateRequestToJSON(requestParameters['importCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Create Import
     */
    async createImport(requestParameters: CreateImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.createImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Import
     */
    async getImportRaw(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling getImport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Get Import
     */
    async getImport(requestParameters: GetImportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.getImportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
