/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  ImportCreateRequest,
  ImportResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    ImportCreateRequestFromJSON,
    ImportCreateRequestToJSON,
    ImportResponseFromJSON,
    ImportResponseToJSON,
} from '../models/index';

export interface CancelImportApiV1ImportsImportIdCancelPostRequest {
    importId: string;
}

export interface ConfirmImportApiV1ImportsImportIdConfirmPostRequest {
    importId: string;
}

export interface CreateImportApiV1ImportsPostRequest {
    importCreateRequest: ImportCreateRequest;
}

export interface GetImportApiV1ImportsImportIdGetRequest {
    importId: string;
}

/**
 * 
 */
export class ImportsApi extends runtime.BaseAPI {

    /**
     * Cancel Import
     */
    async cancelImportApiV1ImportsImportIdCancelPostRaw(requestParameters: CancelImportApiV1ImportsImportIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling cancelImportApiV1ImportsImportIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}/cancel`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Import
     */
    async cancelImportApiV1ImportsImportIdCancelPost(requestParameters: CancelImportApiV1ImportsImportIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.cancelImportApiV1ImportsImportIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Confirm Import
     */
    async confirmImportApiV1ImportsImportIdConfirmPostRaw(requestParameters: ConfirmImportApiV1ImportsImportIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling confirmImportApiV1ImportsImportIdConfirmPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}/confirm`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Confirm Import
     */
    async confirmImportApiV1ImportsImportIdConfirmPost(requestParameters: ConfirmImportApiV1ImportsImportIdConfirmPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.confirmImportApiV1ImportsImportIdConfirmPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Import
     */
    async createImportApiV1ImportsPostRaw(requestParameters: CreateImportApiV1ImportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'importCreateRequest',
                'Required parameter "importCreateRequest" was null or undefined when calling createImportApiV1ImportsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportCreateRequestToJSON(requestParameters['importCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Create Import
     */
    async createImportApiV1ImportsPost(requestParameters: CreateImportApiV1ImportsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.createImportApiV1ImportsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Import
     */
    async getImportApiV1ImportsImportIdGetRaw(requestParameters: GetImportApiV1ImportsImportIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportResponse>> {
        if (requestParameters['importId'] == null) {
            throw new runtime.RequiredError(
                'importId',
                'Required parameter "importId" was null or undefined when calling getImportApiV1ImportsImportIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/imports/{import_id}`.replace(`{${"import_id"}}`, encodeURIComponent(String(requestParameters['importId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportResponseFromJSON(jsonValue));
    }

    /**
     * Get Import
     */
    async getImportApiV1ImportsImportIdGet(requestParameters: GetImportApiV1ImportsImportIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportResponse> {
        const response = await this.getImportApiV1ImportsImportIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
