/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiRequestLogsListResponse,
  HTTPValidationError,
} from '../models/index';
import {
    ApiRequestLogsListResponseFromJSON,
    ApiRequestLogsListResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ListLogsApiV1LogsGetRequest {
    status?: string;
    limit?: number;
}

/**
 * 
 */
export class LogsApi extends runtime.BaseAPI {

    /**
     * List Logs
     */
    async listLogsApiV1LogsGetRaw(requestParameters: ListLogsApiV1LogsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiRequestLogsListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/logs`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiRequestLogsListResponseFromJSON(jsonValue));
    }

    /**
     * List Logs
     */
    async listLogsApiV1LogsGet(requestParameters: ListLogsApiV1LogsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiRequestLogsListResponse> {
        const response = await this.listLogsApiV1LogsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
