/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  PaymentCreateRequest,
  PaymentPatchRequest,
  PaymentResponse,
  PaymentsListResponse,
  SimpleBoolResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    PaymentCreateRequestFromJSON,
    PaymentCreateRequestToJSON,
    PaymentPatchRequestFromJSON,
    PaymentPatchRequestToJSON,
    PaymentResponseFromJSON,
    PaymentResponseToJSON,
    PaymentsListResponseFromJSON,
    PaymentsListResponseToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
} from '../models/index';

export interface CreateDocumentPaymentRequest {
    documentId: string;
    paymentCreateRequest: PaymentCreateRequest;
}

export interface DeletePaymentRequest {
    paymentId: string;
}

export interface GetPaymentRequest {
    paymentId: string;
}

export interface ListDocumentPaymentsRequest {
    documentId: string;
    limit?: number;
    cursor?: string | null;
}

export interface UpdatePaymentRequest {
    paymentId: string;
    paymentPatchRequest: PaymentPatchRequest;
}

/**
 * 
 */
export class PaymentsApi extends runtime.BaseAPI {

    /**
     * Create Document Payment
     */
    async createDocumentPaymentRaw(requestParameters: CreateDocumentPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling createDocumentPayment().'
            );
        }

        if (requestParameters['paymentCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentCreateRequest',
                'Required parameter "paymentCreateRequest" was null or undefined when calling createDocumentPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{document_id}/payments`.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentCreateRequestToJSON(requestParameters['paymentCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     * Create Document Payment
     */
    async createDocumentPayment(requestParameters: CreateDocumentPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.createDocumentPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Payment
     */
    async deletePaymentRaw(requestParameters: DeletePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling deletePayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/{payment_id}`.replace(`{${"payment_id"}}`, encodeURIComponent(String(requestParameters['paymentId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Payment
     */
    async deletePayment(requestParameters: DeletePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deletePaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Payment
     */
    async getPaymentRaw(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling getPayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/{payment_id}`.replace(`{${"payment_id"}}`, encodeURIComponent(String(requestParameters['paymentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     * Get Payment
     */
    async getPayment(requestParameters: GetPaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.getPaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Document Payments
     */
    async listDocumentPaymentsRaw(requestParameters: ListDocumentPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentsListResponse>> {
        if (requestParameters['documentId'] == null) {
            throw new runtime.RequiredError(
                'documentId',
                'Required parameter "documentId" was null or undefined when calling listDocumentPayments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/documents/{document_id}/payments`.replace(`{${"document_id"}}`, encodeURIComponent(String(requestParameters['documentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentsListResponseFromJSON(jsonValue));
    }

    /**
     * List Document Payments
     */
    async listDocumentPayments(requestParameters: ListDocumentPaymentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentsListResponse> {
        const response = await this.listDocumentPaymentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Payment
     */
    async updatePaymentRaw(requestParameters: UpdatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaymentResponse>> {
        if (requestParameters['paymentId'] == null) {
            throw new runtime.RequiredError(
                'paymentId',
                'Required parameter "paymentId" was null or undefined when calling updatePayment().'
            );
        }

        if (requestParameters['paymentPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'paymentPatchRequest',
                'Required parameter "paymentPatchRequest" was null or undefined when calling updatePayment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/payments/{payment_id}`.replace(`{${"payment_id"}}`, encodeURIComponent(String(requestParameters['paymentId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PaymentPatchRequestToJSON(requestParameters['paymentPatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaymentResponseFromJSON(jsonValue));
    }

    /**
     * Update Payment
     */
    async updatePayment(requestParameters: UpdatePaymentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaymentResponse> {
        const response = await this.updatePaymentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
