/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  InvoicesListResponse,
  RecurringInvoiceCreateRequest,
  RecurringInvoicePatchRequest,
  RecurringInvoiceResponse,
  RecurringInvoicesListResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    InvoicesListResponseFromJSON,
    InvoicesListResponseToJSON,
    RecurringInvoiceCreateRequestFromJSON,
    RecurringInvoiceCreateRequestToJSON,
    RecurringInvoicePatchRequestFromJSON,
    RecurringInvoicePatchRequestToJSON,
    RecurringInvoiceResponseFromJSON,
    RecurringInvoiceResponseToJSON,
    RecurringInvoicesListResponseFromJSON,
    RecurringInvoicesListResponseToJSON,
} from '../models/index';

export interface CancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDeleteRequest {
    recurringId: string;
}

export interface CreateRecurringInvoiceApiV1RecurringInvoicesPostRequest {
    recurringInvoiceCreateRequest: RecurringInvoiceCreateRequest;
}

export interface GetRecurringInvoiceApiV1RecurringInvoicesRecurringIdGetRequest {
    recurringId: string;
}

export interface ListGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGetRequest {
    recurringId: string;
    limit?: number;
    cursor?: string | null;
}

export interface ListRecurringInvoicesApiV1RecurringInvoicesGetRequest {
    limit?: number;
    cursor?: string | null;
    status?: string | null;
}

export interface PatchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatchRequest {
    recurringId: string;
    recurringInvoicePatchRequest: RecurringInvoicePatchRequest;
}

export interface PauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePostRequest {
    recurringId: string;
}

export interface ResumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePostRequest {
    recurringId: string;
}

/**
 * 
 */
export class RecurringInvoicesApi extends runtime.BaseAPI {

    /**
     * Cancel Recurring Invoice
     */
    async cancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDeleteRaw(requestParameters: CancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling cancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Recurring Invoice
     */
    async cancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDelete(requestParameters: CancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.cancelRecurringInvoiceApiV1RecurringInvoicesRecurringIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create Recurring Invoice
     */
    async createRecurringInvoiceApiV1RecurringInvoicesPostRaw(requestParameters: CreateRecurringInvoiceApiV1RecurringInvoicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringInvoiceCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'recurringInvoiceCreateRequest',
                'Required parameter "recurringInvoiceCreateRequest" was null or undefined when calling createRecurringInvoiceApiV1RecurringInvoicesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringInvoiceCreateRequestToJSON(requestParameters['recurringInvoiceCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Create Recurring Invoice
     */
    async createRecurringInvoiceApiV1RecurringInvoicesPost(requestParameters: CreateRecurringInvoiceApiV1RecurringInvoicesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.createRecurringInvoiceApiV1RecurringInvoicesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Recurring Invoice
     */
    async getRecurringInvoiceApiV1RecurringInvoicesRecurringIdGetRaw(requestParameters: GetRecurringInvoiceApiV1RecurringInvoicesRecurringIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling getRecurringInvoiceApiV1RecurringInvoicesRecurringIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Get Recurring Invoice
     */
    async getRecurringInvoiceApiV1RecurringInvoicesRecurringIdGet(requestParameters: GetRecurringInvoiceApiV1RecurringInvoicesRecurringIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.getRecurringInvoiceApiV1RecurringInvoicesRecurringIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Generated Invoices
     */
    async listGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGetRaw(requestParameters: ListGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoicesListResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling listGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}/invoices`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoicesListResponseFromJSON(jsonValue));
    }

    /**
     * List Generated Invoices
     */
    async listGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGet(requestParameters: ListGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoicesListResponse> {
        const response = await this.listGeneratedInvoicesApiV1RecurringInvoicesRecurringIdInvoicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Recurring Invoices
     */
    async listRecurringInvoicesApiV1RecurringInvoicesGetRaw(requestParameters: ListRecurringInvoicesApiV1RecurringInvoicesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoicesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoicesListResponseFromJSON(jsonValue));
    }

    /**
     * List Recurring Invoices
     */
    async listRecurringInvoicesApiV1RecurringInvoicesGet(requestParameters: ListRecurringInvoicesApiV1RecurringInvoicesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoicesListResponse> {
        const response = await this.listRecurringInvoicesApiV1RecurringInvoicesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Patch Recurring Invoice
     */
    async patchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatchRaw(requestParameters: PatchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling patchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatch().'
            );
        }

        if (requestParameters['recurringInvoicePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'recurringInvoicePatchRequest',
                'Required parameter "recurringInvoicePatchRequest" was null or undefined when calling patchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: RecurringInvoicePatchRequestToJSON(requestParameters['recurringInvoicePatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Patch Recurring Invoice
     */
    async patchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatch(requestParameters: PatchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.patchRecurringInvoiceApiV1RecurringInvoicesRecurringIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pause Recurring Invoice
     */
    async pauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePostRaw(requestParameters: PauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling pauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}/pause`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Pause Recurring Invoice
     */
    async pauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePost(requestParameters: PauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.pauseRecurringInvoiceApiV1RecurringInvoicesRecurringIdPausePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resume Recurring Invoice
     */
    async resumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePostRaw(requestParameters: ResumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RecurringInvoiceResponse>> {
        if (requestParameters['recurringId'] == null) {
            throw new runtime.RequiredError(
                'recurringId',
                'Required parameter "recurringId" was null or undefined when calling resumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/recurring-invoices/{recurring_id}/resume`.replace(`{${"recurring_id"}}`, encodeURIComponent(String(requestParameters['recurringId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RecurringInvoiceResponseFromJSON(jsonValue));
    }

    /**
     * Resume Recurring Invoice
     */
    async resumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePost(requestParameters: ResumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RecurringInvoiceResponse> {
        const response = await this.resumeRecurringInvoiceApiV1RecurringInvoicesRecurringIdResumePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
