/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  SimpleBoolResponse,
  TaxRateCreateRequest,
  TaxRatePatchRequest,
  TaxRateResponse,
  TaxRatesListResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
    TaxRateCreateRequestFromJSON,
    TaxRateCreateRequestToJSON,
    TaxRatePatchRequestFromJSON,
    TaxRatePatchRequestToJSON,
    TaxRateResponseFromJSON,
    TaxRateResponseToJSON,
    TaxRatesListResponseFromJSON,
    TaxRatesListResponseToJSON,
} from '../models/index';

export interface CreateTaxRateRequest {
    taxRateCreateRequest: TaxRateCreateRequest;
}

export interface DeleteTaxRateRequest {
    taxRateId: string;
}

export interface GetTaxRateRequest {
    taxRateId: string;
}

export interface ListTaxRatesRequest {
    limit?: number;
    cursor?: string | null;
}

export interface UpdateTaxRateRequest {
    taxRateId: string;
    taxRatePatchRequest: TaxRatePatchRequest;
}

/**
 * 
 */
export class TaxRatesApi extends runtime.BaseAPI {

    /**
     * Create Tax Rate
     */
    async createTaxRateRaw(requestParameters: CreateTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaxRateResponse>> {
        if (requestParameters['taxRateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'taxRateCreateRequest',
                'Required parameter "taxRateCreateRequest" was null or undefined when calling createTaxRate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tax-rates`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TaxRateCreateRequestToJSON(requestParameters['taxRateCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaxRateResponseFromJSON(jsonValue));
    }

    /**
     * Create Tax Rate
     */
    async createTaxRate(requestParameters: CreateTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaxRateResponse> {
        const response = await this.createTaxRateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Tax Rate
     */
    async deleteTaxRateRaw(requestParameters: DeleteTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['taxRateId'] == null) {
            throw new runtime.RequiredError(
                'taxRateId',
                'Required parameter "taxRateId" was null or undefined when calling deleteTaxRate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tax-rates/{tax_rate_id}`.replace(`{${"tax_rate_id"}}`, encodeURIComponent(String(requestParameters['taxRateId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Tax Rate
     */
    async deleteTaxRate(requestParameters: DeleteTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteTaxRateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Tax Rate
     */
    async getTaxRateRaw(requestParameters: GetTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaxRateResponse>> {
        if (requestParameters['taxRateId'] == null) {
            throw new runtime.RequiredError(
                'taxRateId',
                'Required parameter "taxRateId" was null or undefined when calling getTaxRate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tax-rates/{tax_rate_id}`.replace(`{${"tax_rate_id"}}`, encodeURIComponent(String(requestParameters['taxRateId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaxRateResponseFromJSON(jsonValue));
    }

    /**
     * Get Tax Rate
     */
    async getTaxRate(requestParameters: GetTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaxRateResponse> {
        const response = await this.getTaxRateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Tax Rates
     */
    async listTaxRatesRaw(requestParameters: ListTaxRatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaxRatesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tax-rates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaxRatesListResponseFromJSON(jsonValue));
    }

    /**
     * List Tax Rates
     */
    async listTaxRates(requestParameters: ListTaxRatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaxRatesListResponse> {
        const response = await this.listTaxRatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Tax Rate
     */
    async updateTaxRateRaw(requestParameters: UpdateTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TaxRateResponse>> {
        if (requestParameters['taxRateId'] == null) {
            throw new runtime.RequiredError(
                'taxRateId',
                'Required parameter "taxRateId" was null or undefined when calling updateTaxRate().'
            );
        }

        if (requestParameters['taxRatePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'taxRatePatchRequest',
                'Required parameter "taxRatePatchRequest" was null or undefined when calling updateTaxRate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/tax-rates/{tax_rate_id}`.replace(`{${"tax_rate_id"}}`, encodeURIComponent(String(requestParameters['taxRateId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TaxRatePatchRequestToJSON(requestParameters['taxRatePatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TaxRateResponseFromJSON(jsonValue));
    }

    /**
     * Update Tax Rate
     */
    async updateTaxRate(requestParameters: UpdateTaxRateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TaxRateResponse> {
        const response = await this.updateTaxRateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
