/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiErrorResponse,
  CustomTemplateResponse,
  CustomTemplatesListResponse,
  DocumentRenderRequest,
  RenderResponse,
  TemplateCreateRequest,
  TemplateDetailResponse,
  TemplatePatchRequest,
  TemplatesListResponse,
} from '../models/index';
import {
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    CustomTemplateResponseFromJSON,
    CustomTemplateResponseToJSON,
    CustomTemplatesListResponseFromJSON,
    CustomTemplatesListResponseToJSON,
    DocumentRenderRequestFromJSON,
    DocumentRenderRequestToJSON,
    RenderResponseFromJSON,
    RenderResponseToJSON,
    TemplateCreateRequestFromJSON,
    TemplateCreateRequestToJSON,
    TemplateDetailResponseFromJSON,
    TemplateDetailResponseToJSON,
    TemplatePatchRequestFromJSON,
    TemplatePatchRequestToJSON,
    TemplatesListResponseFromJSON,
    TemplatesListResponseToJSON,
} from '../models/index';

export interface CreateTemplateRequest {
    templateCreateRequest: TemplateCreateRequest;
}

export interface DeleteTemplateRequest {
    templateId: string;
}

export interface DuplicateTemplateRequest {
    templateId: string;
}

export interface GetBuiltinTemplateRequest {
    templateId: string;
}

export interface GetCustomTemplateRequest {
    templateId: string;
}

export interface GetTemplateRequest {
    templateId: string;
}

export interface ListCustomTemplatesRequest {
    limit?: number;
    cursor?: string | null;
}

export interface PreviewTemplateRequest {
    templateId: string;
    documentRenderRequest: DocumentRenderRequest;
    idempotencyKey?: string | null;
}

export interface PublishTemplateRequest {
    templateId: string;
}

export interface UpdateTemplateRequest {
    templateId: string;
    templatePatchRequest: TemplatePatchRequest;
}

/**
 * 
 */
export class TemplatesApi extends runtime.BaseAPI {

    /**
     * Create Template
     */
    async createTemplateRaw(requestParameters: CreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplateResponse>> {
        if (requestParameters['templateCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'templateCreateRequest',
                'Required parameter "templateCreateRequest" was null or undefined when calling createTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TemplateCreateRequestToJSON(requestParameters['templateCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Create Template
     */
    async createTemplate(requestParameters: CreateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplateResponse> {
        const response = await this.createTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Template
     */
    async deleteTemplateRaw(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling deleteTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom/{template_id}`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete Template
     */
    async deleteTemplate(requestParameters: DeleteTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteTemplateRaw(requestParameters, initOverrides);
    }

    /**
     * Duplicate Template
     */
    async duplicateTemplateRaw(requestParameters: DuplicateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplateResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling duplicateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom/{template_id}/duplicate`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Duplicate Template
     */
    async duplicateTemplate(requestParameters: DuplicateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplateResponse> {
        const response = await this.duplicateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Builtin Template
     */
    async getBuiltinTemplateRaw(requestParameters: GetBuiltinTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateDetailResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getBuiltinTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/builtin/{template_id}`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get Builtin Template
     */
    async getBuiltinTemplate(requestParameters: GetBuiltinTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateDetailResponse> {
        const response = await this.getBuiltinTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Custom Template
     */
    async getCustomTemplateRaw(requestParameters: GetCustomTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplateResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getCustomTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom/{template_id}`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Get Custom Template
     */
    async getCustomTemplate(requestParameters: GetCustomTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplateResponse> {
        const response = await this.getCustomTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Template
     */
    async getTemplateRaw(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplateDetailResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling getTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/{template_id}`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplateDetailResponseFromJSON(jsonValue));
    }

    /**
     * Get Template
     */
    async getTemplate(requestParameters: GetTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplateDetailResponse> {
        const response = await this.getTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Custom Templates
     */
    async listCustomTemplatesRaw(requestParameters: ListCustomTemplatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplatesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplatesListResponseFromJSON(jsonValue));
    }

    /**
     * List Custom Templates
     */
    async listCustomTemplates(requestParameters: ListCustomTemplatesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplatesListResponse> {
        const response = await this.listCustomTemplatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Templates
     */
    async listTemplatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TemplatesListResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TemplatesListResponseFromJSON(jsonValue));
    }

    /**
     * List Templates
     */
    async listTemplates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TemplatesListResponse> {
        const response = await this.listTemplatesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Preview Template
     */
    async previewTemplateRaw(requestParameters: PreviewTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RenderResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling previewTemplate().'
            );
        }

        if (requestParameters['documentRenderRequest'] == null) {
            throw new runtime.RequiredError(
                'documentRenderRequest',
                'Required parameter "documentRenderRequest" was null or undefined when calling previewTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/{template_id}/preview`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DocumentRenderRequestToJSON(requestParameters['documentRenderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RenderResponseFromJSON(jsonValue));
    }

    /**
     * Preview Template
     */
    async previewTemplate(requestParameters: PreviewTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RenderResponse> {
        const response = await this.previewTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Publish Template
     */
    async publishTemplateRaw(requestParameters: PublishTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplateResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling publishTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom/{template_id}/publish`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Publish Template
     */
    async publishTemplate(requestParameters: PublishTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplateResponse> {
        const response = await this.publishTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Template
     */
    async updateTemplateRaw(requestParameters: UpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomTemplateResponse>> {
        if (requestParameters['templateId'] == null) {
            throw new runtime.RequiredError(
                'templateId',
                'Required parameter "templateId" was null or undefined when calling updateTemplate().'
            );
        }

        if (requestParameters['templatePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'templatePatchRequest',
                'Required parameter "templatePatchRequest" was null or undefined when calling updateTemplate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/templates/custom/{template_id}`.replace(`{${"template_id"}}`, encodeURIComponent(String(requestParameters['templateId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TemplatePatchRequestToJSON(requestParameters['templatePatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomTemplateResponseFromJSON(jsonValue));
    }

    /**
     * Update Template
     */
    async updateTemplate(requestParameters: UpdateTemplateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomTemplateResponse> {
        const response = await this.updateTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
