/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  SimpleBoolResponse,
  WebhookDeliveriesListResponse,
  WebhookDeliveryResponse,
  WebhookEndpointCreateRequest,
  WebhookEndpointPatchRequest,
  WebhookEndpointResponse,
  WebhookEndpointsListResponse,
  WebhookSecretResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SimpleBoolResponseFromJSON,
    SimpleBoolResponseToJSON,
    WebhookDeliveriesListResponseFromJSON,
    WebhookDeliveriesListResponseToJSON,
    WebhookDeliveryResponseFromJSON,
    WebhookDeliveryResponseToJSON,
    WebhookEndpointCreateRequestFromJSON,
    WebhookEndpointCreateRequestToJSON,
    WebhookEndpointPatchRequestFromJSON,
    WebhookEndpointPatchRequestToJSON,
    WebhookEndpointResponseFromJSON,
    WebhookEndpointResponseToJSON,
    WebhookEndpointsListResponseFromJSON,
    WebhookEndpointsListResponseToJSON,
    WebhookSecretResponseFromJSON,
    WebhookSecretResponseToJSON,
} from '../models/index';

export interface CreateWebhookEndpointApiV1WebhookEndpointsPostRequest {
    webhookEndpointCreateRequest: WebhookEndpointCreateRequest;
}

export interface DeleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDeleteRequest {
    endpointId: string;
}

export interface GetWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGetRequest {
    deliveryId: string;
}

export interface GetWebhookEndpointApiV1WebhookEndpointsEndpointIdGetRequest {
    endpointId: string;
}

export interface ListWebhookDeliveriesApiV1WebhookDeliveriesGetRequest {
    limit?: number;
    cursor?: string | null;
}

export interface ListWebhookEndpointsApiV1WebhookEndpointsGetRequest {
    limit?: number;
    cursor?: string | null;
}

export interface RetryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPostRequest {
    deliveryId: string;
}

export interface RotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPostRequest {
    endpointId: string;
}

export interface TestWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPostRequest {
    endpointId: string;
}

export interface UpdateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatchRequest {
    endpointId: string;
    webhookEndpointPatchRequest: WebhookEndpointPatchRequest;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Create Webhook Endpoint
     */
    async createWebhookEndpointApiV1WebhookEndpointsPostRaw(requestParameters: CreateWebhookEndpointApiV1WebhookEndpointsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponse>> {
        if (requestParameters['webhookEndpointCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'webhookEndpointCreateRequest',
                'Required parameter "webhookEndpointCreateRequest" was null or undefined when calling createWebhookEndpointApiV1WebhookEndpointsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEndpointCreateRequestToJSON(requestParameters['webhookEndpointCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Create Webhook Endpoint
     */
    async createWebhookEndpointApiV1WebhookEndpointsPost(requestParameters: CreateWebhookEndpointApiV1WebhookEndpointsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponse> {
        const response = await this.createWebhookEndpointApiV1WebhookEndpointsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete Webhook Endpoint
     */
    async deleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDeleteRaw(requestParameters: DeleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleBoolResponse>> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling deleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints/{endpoint_id}`.replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleBoolResponseFromJSON(jsonValue));
    }

    /**
     * Delete Webhook Endpoint
     */
    async deleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDelete(requestParameters: DeleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleBoolResponse> {
        const response = await this.deleteWebhookEndpointApiV1WebhookEndpointsEndpointIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Webhook Delivery
     */
    async getWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGetRaw(requestParameters: GetWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryResponse>> {
        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling getWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-deliveries/{delivery_id}`.replace(`{${"delivery_id"}}`, encodeURIComponent(String(requestParameters['deliveryId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Get Webhook Delivery
     */
    async getWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGet(requestParameters: GetWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryResponse> {
        const response = await this.getWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get Webhook Endpoint
     */
    async getWebhookEndpointApiV1WebhookEndpointsEndpointIdGetRaw(requestParameters: GetWebhookEndpointApiV1WebhookEndpointsEndpointIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponse>> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling getWebhookEndpointApiV1WebhookEndpointsEndpointIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints/{endpoint_id}`.replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Get Webhook Endpoint
     */
    async getWebhookEndpointApiV1WebhookEndpointsEndpointIdGet(requestParameters: GetWebhookEndpointApiV1WebhookEndpointsEndpointIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponse> {
        const response = await this.getWebhookEndpointApiV1WebhookEndpointsEndpointIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Webhook Deliveries
     */
    async listWebhookDeliveriesApiV1WebhookDeliveriesGetRaw(requestParameters: ListWebhookDeliveriesApiV1WebhookDeliveriesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveriesListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-deliveries`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveriesListResponseFromJSON(jsonValue));
    }

    /**
     * List Webhook Deliveries
     */
    async listWebhookDeliveriesApiV1WebhookDeliveriesGet(requestParameters: ListWebhookDeliveriesApiV1WebhookDeliveriesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveriesListResponse> {
        const response = await this.listWebhookDeliveriesApiV1WebhookDeliveriesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List Webhook Endpoints
     */
    async listWebhookEndpointsApiV1WebhookEndpointsGetRaw(requestParameters: ListWebhookEndpointsApiV1WebhookEndpointsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointsListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointsListResponseFromJSON(jsonValue));
    }

    /**
     * List Webhook Endpoints
     */
    async listWebhookEndpointsApiV1WebhookEndpointsGet(requestParameters: ListWebhookEndpointsApiV1WebhookEndpointsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointsListResponse> {
        const response = await this.listWebhookEndpointsApiV1WebhookEndpointsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retry Webhook Delivery
     */
    async retryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPostRaw(requestParameters: RetryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryResponse>> {
        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling retryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-deliveries/{delivery_id}/retry`.replace(`{${"delivery_id"}}`, encodeURIComponent(String(requestParameters['deliveryId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Retry Webhook Delivery
     */
    async retryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPost(requestParameters: RetryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryResponse> {
        const response = await this.retryWebhookDeliveryApiV1WebhookDeliveriesDeliveryIdRetryPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate Webhook Secret
     */
    async rotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPostRaw(requestParameters: RotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookSecretResponse>> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling rotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints/{endpoint_id}/rotate-secret`.replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookSecretResponseFromJSON(jsonValue));
    }

    /**
     * Rotate Webhook Secret
     */
    async rotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPost(requestParameters: RotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookSecretResponse> {
        const response = await this.rotateWebhookSecretApiV1WebhookEndpointsEndpointIdRotateSecretPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Test Webhook Endpoint
     */
    async testWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPostRaw(requestParameters: TestWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryResponse>> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling testWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints/{endpoint_id}/test`.replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Test Webhook Endpoint
     */
    async testWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPost(requestParameters: TestWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryResponse> {
        const response = await this.testWebhookEndpointApiV1WebhookEndpointsEndpointIdTestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update Webhook Endpoint
     */
    async updateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatchRaw(requestParameters: UpdateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponse>> {
        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling updateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatch().'
            );
        }

        if (requestParameters['webhookEndpointPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'webhookEndpointPatchRequest',
                'Required parameter "webhookEndpointPatchRequest" was null or undefined when calling updateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/v1/webhook-endpoints/{endpoint_id}`.replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEndpointPatchRequestToJSON(requestParameters['webhookEndpointPatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Update Webhook Endpoint
     */
    async updateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatch(requestParameters: UpdateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponse> {
        const response = await this.updateWebhookEndpointApiV1WebhookEndpointsEndpointIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
