/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiErrorResponseError } from './ApiErrorResponseError';
import {
    ApiErrorResponseErrorFromJSON,
    ApiErrorResponseErrorFromJSONTyped,
    ApiErrorResponseErrorToJSON,
} from './ApiErrorResponseError';

/**
 * 
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * 
     * @type {ApiErrorResponseError}
     * @memberof ApiErrorResponse
     */
    error: ApiErrorResponseError;
}

/**
 * Check if a given object implements the ApiErrorResponse interface.
 */
export function instanceOfApiErrorResponse(value: object): value is ApiErrorResponse {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'error': ApiErrorResponseErrorFromJSON(json['error']),
    };
}

export function ApiErrorResponseToJSON(value?: ApiErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'error': ApiErrorResponseErrorToJSON(value['error']),
    };
}

