/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyCreated } from './ApiKeyCreated';
import {
    ApiKeyCreatedFromJSON,
    ApiKeyCreatedFromJSONTyped,
    ApiKeyCreatedToJSON,
} from './ApiKeyCreated';

/**
 * 
 * @export
 * @interface ApiKeyCreateResponse
 */
export interface ApiKeyCreateResponse {
    /**
     * 
     * @type {ApiKeyCreated}
     * @memberof ApiKeyCreateResponse
     */
    data: ApiKeyCreated;
}

/**
 * Check if a given object implements the ApiKeyCreateResponse interface.
 */
export function instanceOfApiKeyCreateResponse(value: object): value is ApiKeyCreateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiKeyCreateResponseFromJSON(json: any): ApiKeyCreateResponse {
    return ApiKeyCreateResponseFromJSONTyped(json, false);
}

export function ApiKeyCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ApiKeyCreatedFromJSON(json['data']),
    };
}

export function ApiKeyCreateResponseToJSON(value?: ApiKeyCreateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ApiKeyCreatedToJSON(value['data']),
    };
}

