/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiKeyListItem } from './ApiKeyListItem';
import {
    ApiKeyListItemFromJSON,
    ApiKeyListItemFromJSONTyped,
    ApiKeyListItemToJSON,
} from './ApiKeyListItem';

/**
 * 
 * @export
 * @interface ApiKeyDetailResponse
 */
export interface ApiKeyDetailResponse {
    /**
     * 
     * @type {ApiKeyListItem}
     * @memberof ApiKeyDetailResponse
     */
    data: ApiKeyListItem;
}

/**
 * Check if a given object implements the ApiKeyDetailResponse interface.
 */
export function instanceOfApiKeyDetailResponse(value: object): value is ApiKeyDetailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiKeyDetailResponseFromJSON(json: any): ApiKeyDetailResponse {
    return ApiKeyDetailResponseFromJSONTyped(json, false);
}

export function ApiKeyDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ApiKeyListItemFromJSON(json['data']),
    };
}

export function ApiKeyDetailResponseToJSON(value?: ApiKeyDetailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ApiKeyListItemToJSON(value['data']),
    };
}

