/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyPatchRequest
 */
export interface ApiKeyPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiKeyPatchRequest
     */
    name: string;
}

/**
 * Check if a given object implements the ApiKeyPatchRequest interface.
 */
export function instanceOfApiKeyPatchRequest(value: object): value is ApiKeyPatchRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ApiKeyPatchRequestFromJSON(json: any): ApiKeyPatchRequest {
    return ApiKeyPatchRequestFromJSONTyped(json, false);
}

export function ApiKeyPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ApiKeyPatchRequestToJSON(value?: ApiKeyPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

