/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiRequestLogOut } from './ApiRequestLogOut';
import {
    ApiRequestLogOutFromJSON,
    ApiRequestLogOutFromJSONTyped,
    ApiRequestLogOutToJSON,
} from './ApiRequestLogOut';

/**
 * 
 * @export
 * @interface ApiRequestLogsListResponse
 */
export interface ApiRequestLogsListResponse {
    /**
     * 
     * @type {Array<ApiRequestLogOut>}
     * @memberof ApiRequestLogsListResponse
     */
    data: Array<ApiRequestLogOut>;
}

/**
 * Check if a given object implements the ApiRequestLogsListResponse interface.
 */
export function instanceOfApiRequestLogsListResponse(value: object): value is ApiRequestLogsListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ApiRequestLogsListResponseFromJSON(json: any): ApiRequestLogsListResponse {
    return ApiRequestLogsListResponseFromJSONTyped(json, false);
}

export function ApiRequestLogsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRequestLogsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ApiRequestLogOutFromJSON)),
    };
}

export function ApiRequestLogsListResponseToJSON(value?: ApiRequestLogsListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(ApiRequestLogOutToJSON)),
    };
}

