/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppDocumentsSchemasDocumentRenderRequest
 */
export interface AppDocumentsSchemasDocumentRenderRequest {
    /**
     * 
     * @type {string}
     * @memberof AppDocumentsSchemasDocumentRenderRequest
     */
    templateId?: string;
    /**
     * 
     * @type {string}
     * @memberof AppDocumentsSchemasDocumentRenderRequest
     */
    pageSize?: string;
    /**
     * 
     * @type {number}
     * @memberof AppDocumentsSchemasDocumentRenderRequest
     */
    expiresIn?: number;
}

/**
 * Check if a given object implements the AppDocumentsSchemasDocumentRenderRequest interface.
 */
export function instanceOfAppDocumentsSchemasDocumentRenderRequest(value: object): value is AppDocumentsSchemasDocumentRenderRequest {
    return true;
}

export function AppDocumentsSchemasDocumentRenderRequestFromJSON(json: any): AppDocumentsSchemasDocumentRenderRequest {
    return AppDocumentsSchemasDocumentRenderRequestFromJSONTyped(json, false);
}

export function AppDocumentsSchemasDocumentRenderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppDocumentsSchemasDocumentRenderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
    };
}

export function AppDocumentsSchemasDocumentRenderRequestToJSON(value?: AppDocumentsSchemasDocumentRenderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'template_id': value['templateId'],
        'page_size': value['pageSize'],
        'expires_in': value['expiresIn'],
    };
}

