/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEventOut } from './AuditEventOut';
import {
    AuditEventOutFromJSON,
    AuditEventOutFromJSONTyped,
    AuditEventOutToJSON,
} from './AuditEventOut';

/**
 * 
 * @export
 * @interface AuditEventResponse
 */
export interface AuditEventResponse {
    /**
     * 
     * @type {AuditEventOut}
     * @memberof AuditEventResponse
     */
    data: AuditEventOut;
}

/**
 * Check if a given object implements the AuditEventResponse interface.
 */
export function instanceOfAuditEventResponse(value: object): value is AuditEventResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuditEventResponseFromJSON(json: any): AuditEventResponse {
    return AuditEventResponseFromJSONTyped(json, false);
}

export function AuditEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AuditEventOutFromJSON(json['data']),
    };
}

export function AuditEventResponseToJSON(value?: AuditEventResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AuditEventOutToJSON(value['data']),
    };
}

