/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthMeData } from './AuthMeData';
import {
    AuthMeDataFromJSON,
    AuthMeDataFromJSONTyped,
    AuthMeDataToJSON,
} from './AuthMeData';

/**
 * 
 * @export
 * @interface AuthMeResponse
 */
export interface AuthMeResponse {
    /**
     * 
     * @type {AuthMeData}
     * @memberof AuthMeResponse
     */
    data: AuthMeData;
}

/**
 * Check if a given object implements the AuthMeResponse interface.
 */
export function instanceOfAuthMeResponse(value: object): value is AuthMeResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuthMeResponseFromJSON(json: any): AuthMeResponse {
    return AuthMeResponseFromJSONTyped(json, false);
}

export function AuthMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AuthMeDataFromJSON(json['data']),
    };
}

export function AuthMeResponseToJSON(value?: AuthMeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AuthMeDataToJSON(value['data']),
    };
}

