/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMePatchRequest
 */
export interface AuthMePatchRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthMePatchRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthMePatchRequest
     */
    email?: string | null;
}

/**
 * Check if a given object implements the AuthMePatchRequest interface.
 */
export function instanceOfAuthMePatchRequest(value: object): value is AuthMePatchRequest {
    return true;
}

export function AuthMePatchRequestFromJSON(json: any): AuthMePatchRequest {
    return AuthMePatchRequestFromJSONTyped(json, false);
}

export function AuthMePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function AuthMePatchRequestToJSON(value?: AuthMePatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

