/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthAccountData
 */
export interface AuthAccountData {
    /**
     * 
     * @type {string}
     * @memberof AuthAccountData
     */
    accountId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAccountData
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAccountData
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthAccountData
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthAccountData
     */
    planName: string;
}

/**
 * Check if a given object implements the AuthAccountData interface.
 */
export function instanceOfAuthAccountData(value: object): value is AuthAccountData {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('planName' in value) || value['planName'] === undefined) return false;
    return true;
}

export function AuthAccountDataFromJSON(json: any): AuthAccountData {
    return AuthAccountDataFromJSONTyped(json, false);
}

export function AuthAccountDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthAccountData {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'name': json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'planId': json['plan_id'],
        'planName': json['plan_name'],
    };
}

export function AuthAccountDataToJSON(value?: AuthAccountData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account_id': value['accountId'],
        'name': value['name'],
        'email': value['email'],
        'plan_id': value['planId'],
        'plan_name': value['planName'],
    };
}

