/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthMeAccount
 */
export interface AuthMeAccount {
    /**
     * 
     * @type {string}
     * @memberof AuthMeAccount
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeAccount
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeAccount
     */
    planId: string;
    /**
     * 
     * @type {string}
     * @memberof AuthMeAccount
     */
    planName: string;
}

/**
 * Check if a given object implements the AuthMeAccount interface.
 */
export function instanceOfAuthMeAccount(value: object): value is AuthMeAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('planId' in value) || value['planId'] === undefined) return false;
    if (!('planName' in value) || value['planName'] === undefined) return false;
    return true;
}

export function AuthMeAccountFromJSON(json: any): AuthMeAccount {
    return AuthMeAccountFromJSONTyped(json, false);
}

export function AuthMeAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthMeAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'planId': json['plan_id'],
        'planName': json['plan_name'],
    };
}

export function AuthMeAccountToJSON(value?: AuthMeAccount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'plan_id': value['planId'],
        'plan_name': value['planName'],
    };
}

