/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthAccountData } from './AuthAccountData';
import {
    AuthAccountDataFromJSON,
    AuthAccountDataFromJSONTyped,
    AuthAccountDataToJSON,
} from './AuthAccountData';

/**
 * 
 * @export
 * @interface AuthRegisterResponse
 */
export interface AuthRegisterResponse {
    /**
     * 
     * @type {AuthAccountData}
     * @memberof AuthRegisterResponse
     */
    data: AuthAccountData;
}

/**
 * Check if a given object implements the AuthRegisterResponse interface.
 */
export function instanceOfAuthRegisterResponse(value: object): value is AuthRegisterResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function AuthRegisterResponseFromJSON(json: any): AuthRegisterResponse {
    return AuthRegisterResponseFromJSONTyped(json, false);
}

export function AuthRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': AuthAccountDataFromJSON(json['data']),
    };
}

export function AuthRegisterResponseToJSON(value?: AuthRegisterResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': AuthAccountDataToJSON(value['data']),
    };
}

