/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BatchStatus = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type BatchStatus = typeof BatchStatus[keyof typeof BatchStatus];


export function instanceOfBatchStatus(value: any): boolean {
    for (const key in BatchStatus) {
        if (Object.prototype.hasOwnProperty.call(BatchStatus, key)) {
            if ((BatchStatus as Record<string, BatchStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BatchStatusFromJSON(json: any): BatchStatus {
    return BatchStatusFromJSONTyped(json, false);
}

export function BatchStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchStatus {
    return json as BatchStatus;
}

export function BatchStatusToJSON(value?: BatchStatus | null): any {
    return value as any;
}

