/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchOutputOptions } from './BatchOutputOptions';
import {
    BatchOutputOptionsFromJSON,
    BatchOutputOptionsFromJSONTyped,
    BatchOutputOptionsToJSON,
} from './BatchOutputOptions';
import type { BatchItemInput } from './BatchItemInput';
import {
    BatchItemInputFromJSON,
    BatchItemInputFromJSONTyped,
    BatchItemInputToJSON,
} from './BatchItemInput';

/**
 * 
 * @export
 * @interface BatchCreateRequest
 */
export interface BatchCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof BatchCreateRequest
     */
    operation?: BatchCreateRequestOperationEnum;
    /**
     * 
     * @type {Array<BatchItemInput>}
     * @memberof BatchCreateRequest
     */
    items: Array<BatchItemInput>;
    /**
     * 
     * @type {string}
     * @memberof BatchCreateRequest
     */
    templateId?: string;
    /**
     * 
     * @type {BatchOutputOptions}
     * @memberof BatchCreateRequest
     */
    output?: BatchOutputOptions;
}


/**
 * @export
 */
export const BatchCreateRequestOperationEnum = {
    Render: 'render'
} as const;
export type BatchCreateRequestOperationEnum = typeof BatchCreateRequestOperationEnum[keyof typeof BatchCreateRequestOperationEnum];


/**
 * Check if a given object implements the BatchCreateRequest interface.
 */
export function instanceOfBatchCreateRequest(value: object): value is BatchCreateRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function BatchCreateRequestFromJSON(json: any): BatchCreateRequest {
    return BatchCreateRequestFromJSONTyped(json, false);
}

export function BatchCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'operation': json['operation'] == null ? undefined : json['operation'],
        'items': ((json['items'] as Array<any>).map(BatchItemInputFromJSON)),
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'output': json['output'] == null ? undefined : BatchOutputOptionsFromJSON(json['output']),
    };
}

export function BatchCreateRequestToJSON(value?: BatchCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'operation': value['operation'],
        'items': ((value['items'] as Array<any>).map(BatchItemInputToJSON)),
        'template_id': value['templateId'],
        'output': BatchOutputOptionsToJSON(value['output']),
    };
}

