/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchItemInput
 */
export interface BatchItemInput {
    /**
     * 
     * @type {string}
     * @memberof BatchItemInput
     */
    externalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BatchItemInput
     */
    documentType?: BatchItemInputDocumentTypeEnum;
    /**
     * Document data payload
     * @type {{ [key: string]: any; }}
     * @memberof BatchItemInput
     */
    data: { [key: string]: any; };
}


/**
 * @export
 */
export const BatchItemInputDocumentTypeEnum = {
    Invoice: 'invoice'
} as const;
export type BatchItemInputDocumentTypeEnum = typeof BatchItemInputDocumentTypeEnum[keyof typeof BatchItemInputDocumentTypeEnum];


/**
 * Check if a given object implements the BatchItemInput interface.
 */
export function instanceOfBatchItemInput(value: object): value is BatchItemInput {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BatchItemInputFromJSON(json: any): BatchItemInput {
    return BatchItemInputFromJSONTyped(json, false);
}

export function BatchItemInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchItemInput {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['external_id'] == null ? undefined : json['external_id'],
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'data': json['data'],
    };
}

export function BatchItemInputToJSON(value?: BatchItemInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'external_id': value['externalId'],
        'document_type': value['documentType'],
        'data': value['data'],
    };
}

