/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchOut
 */
export interface BatchOut {
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    status: BatchOutStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    operation: string;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    templateId: string;
    /**
     * 
     * @type {number}
     * @memberof BatchOut
     */
    totalItems: number;
    /**
     * 
     * @type {number}
     * @memberof BatchOut
     */
    completedItems: number;
    /**
     * 
     * @type {number}
     * @memberof BatchOut
     */
    failedItems: number;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof BatchOut
     */
    completedAt?: string | null;
}


/**
 * @export
 */
export const BatchOutStatusEnum = {
    Queued: 'queued',
    Processing: 'processing',
    Completed: 'completed',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type BatchOutStatusEnum = typeof BatchOutStatusEnum[keyof typeof BatchOutStatusEnum];


/**
 * Check if a given object implements the BatchOut interface.
 */
export function instanceOfBatchOut(value: object): value is BatchOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('totalItems' in value) || value['totalItems'] === undefined) return false;
    if (!('completedItems' in value) || value['completedItems'] === undefined) return false;
    if (!('failedItems' in value) || value['failedItems'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BatchOutFromJSON(json: any): BatchOut {
    return BatchOutFromJSONTyped(json, false);
}

export function BatchOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'operation': json['operation'],
        'templateId': json['template_id'],
        'totalItems': json['total_items'],
        'completedItems': json['completed_items'],
        'failedItems': json['failed_items'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'completedAt': json['completed_at'] == null ? undefined : json['completed_at'],
    };
}

export function BatchOutToJSON(value?: BatchOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': value['status'],
        'operation': value['operation'],
        'template_id': value['templateId'],
        'total_items': value['totalItems'],
        'completed_items': value['completedItems'],
        'failed_items': value['failedItems'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
        'completed_at': value['completedAt'],
    };
}

