/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BatchOutputOptions
 */
export interface BatchOutputOptions {
    /**
     * 
     * @type {string}
     * @memberof BatchOutputOptions
     */
    format?: BatchOutputOptionsFormatEnum;
    /**
     * 
     * @type {boolean}
     * @memberof BatchOutputOptions
     */
    combine?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BatchOutputOptions
     */
    archiveFormat?: BatchOutputOptionsArchiveFormatEnum;
}


/**
 * @export
 */
export const BatchOutputOptionsFormatEnum = {
    Pdf: 'pdf'
} as const;
export type BatchOutputOptionsFormatEnum = typeof BatchOutputOptionsFormatEnum[keyof typeof BatchOutputOptionsFormatEnum];

/**
 * @export
 */
export const BatchOutputOptionsArchiveFormatEnum = {
    Zip: 'zip'
} as const;
export type BatchOutputOptionsArchiveFormatEnum = typeof BatchOutputOptionsArchiveFormatEnum[keyof typeof BatchOutputOptionsArchiveFormatEnum];


/**
 * Check if a given object implements the BatchOutputOptions interface.
 */
export function instanceOfBatchOutputOptions(value: object): value is BatchOutputOptions {
    return true;
}

export function BatchOutputOptionsFromJSON(json: any): BatchOutputOptions {
    return BatchOutputOptionsFromJSONTyped(json, false);
}

export function BatchOutputOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchOutputOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'] == null ? undefined : json['format'],
        'combine': json['combine'] == null ? undefined : json['combine'],
        'archiveFormat': json['archive_format'] == null ? undefined : json['archive_format'],
    };
}

export function BatchOutputOptionsToJSON(value?: BatchOutputOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'format': value['format'],
        'combine': value['combine'],
        'archive_format': value['archiveFormat'],
    };
}

