/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingSubscriptionData } from './BillingSubscriptionData';
import {
    BillingSubscriptionDataFromJSON,
    BillingSubscriptionDataFromJSONTyped,
    BillingSubscriptionDataToJSON,
} from './BillingSubscriptionData';

/**
 * 
 * @export
 * @interface BillingSubscriptionResponse
 */
export interface BillingSubscriptionResponse {
    /**
     * 
     * @type {BillingSubscriptionData}
     * @memberof BillingSubscriptionResponse
     */
    data: BillingSubscriptionData;
}

/**
 * Check if a given object implements the BillingSubscriptionResponse interface.
 */
export function instanceOfBillingSubscriptionResponse(value: object): value is BillingSubscriptionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BillingSubscriptionResponseFromJSON(json: any): BillingSubscriptionResponse {
    return BillingSubscriptionResponseFromJSONTyped(json, false);
}

export function BillingSubscriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingSubscriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BillingSubscriptionDataFromJSON(json['data']),
    };
}

export function BillingSubscriptionResponseToJSON(value?: BillingSubscriptionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': BillingSubscriptionDataToJSON(value['data']),
    };
}

