/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingCheckoutRequest
 */
export interface BillingCheckoutRequest {
    /**
     * Stripe price ID for the plan
     * @type {string}
     * @memberof BillingCheckoutRequest
     */
    priceId: string;
}

/**
 * Check if a given object implements the BillingCheckoutRequest interface.
 */
export function instanceOfBillingCheckoutRequest(value: object): value is BillingCheckoutRequest {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    return true;
}

export function BillingCheckoutRequestFromJSON(json: any): BillingCheckoutRequest {
    return BillingCheckoutRequestFromJSONTyped(json, false);
}

export function BillingCheckoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingCheckoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['price_id'],
    };
}

export function BillingCheckoutRequestToJSON(value?: BillingCheckoutRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'price_id': value['priceId'],
    };
}

