/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BillingOverageData } from './BillingOverageData';
import {
    BillingOverageDataFromJSON,
    BillingOverageDataFromJSONTyped,
    BillingOverageDataToJSON,
} from './BillingOverageData';

/**
 * 
 * @export
 * @interface BillingOverageResponse
 */
export interface BillingOverageResponse {
    /**
     * 
     * @type {BillingOverageData}
     * @memberof BillingOverageResponse
     */
    data: BillingOverageData;
}

/**
 * Check if a given object implements the BillingOverageResponse interface.
 */
export function instanceOfBillingOverageResponse(value: object): value is BillingOverageResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BillingOverageResponseFromJSON(json: any): BillingOverageResponse {
    return BillingOverageResponseFromJSONTyped(json, false);
}

export function BillingOverageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingOverageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BillingOverageDataFromJSON(json['data']),
    };
}

export function BillingOverageResponseToJSON(value?: BillingOverageResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': BillingOverageDataToJSON(value['data']),
    };
}

