/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BillingPlan
 */
export interface BillingPlan {
    /**
     * 
     * @type {string}
     * @memberof BillingPlan
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPlan
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPlan
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof BillingPlan
     */
    priceIdAnnual?: string | null;
    /**
     * 
     * @type {number}
     * @memberof BillingPlan
     */
    monthlyRenderQuota: number;
    /**
     * 
     * @type {boolean}
     * @memberof BillingPlan
     */
    allowBrandingRemoval?: boolean;
    /**
     * 
     * @type {number}
     * @memberof BillingPlan
     */
    overagePriceMillicents?: number | null;
}

/**
 * Check if a given object implements the BillingPlan interface.
 */
export function instanceOfBillingPlan(value: object): value is BillingPlan {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('monthlyRenderQuota' in value) || value['monthlyRenderQuota'] === undefined) return false;
    return true;
}

export function BillingPlanFromJSON(json: any): BillingPlan {
    return BillingPlanFromJSONTyped(json, false);
}

export function BillingPlanFromJSONTyped(json: any, ignoreDiscriminator: boolean): BillingPlan {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'priceId': json['price_id'],
        'priceIdAnnual': json['price_id_annual'] == null ? undefined : json['price_id_annual'],
        'monthlyRenderQuota': json['monthly_render_quota'],
        'allowBrandingRemoval': json['allow_branding_removal'] == null ? undefined : json['allow_branding_removal'],
        'overagePriceMillicents': json['overage_price_millicents'] == null ? undefined : json['overage_price_millicents'],
    };
}

export function BillingPlanToJSON(value?: BillingPlan | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'price_id': value['priceId'],
        'price_id_annual': value['priceIdAnnual'],
        'monthly_render_quota': value['monthlyRenderQuota'],
        'allow_branding_removal': value['allowBrandingRemoval'],
        'overage_price_millicents': value['overagePriceMillicents'],
    };
}

