/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BrandingUpdateRequest
 */
export interface BrandingUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof BrandingUpdateRequest
     */
    primaryColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandingUpdateRequest
     */
    accentColor?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandingUpdateRequest
     */
    fontFamily?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BrandingUpdateRequest
     */
    footerText?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof BrandingUpdateRequest
     */
    hideInvoicepdfsBranding?: boolean | null;
}

/**
 * Check if a given object implements the BrandingUpdateRequest interface.
 */
export function instanceOfBrandingUpdateRequest(value: object): value is BrandingUpdateRequest {
    return true;
}

export function BrandingUpdateRequestFromJSON(json: any): BrandingUpdateRequest {
    return BrandingUpdateRequestFromJSONTyped(json, false);
}

export function BrandingUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BrandingUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'primaryColor': json['primary_color'] == null ? undefined : json['primary_color'],
        'accentColor': json['accent_color'] == null ? undefined : json['accent_color'],
        'fontFamily': json['font_family'] == null ? undefined : json['font_family'],
        'footerText': json['footer_text'] == null ? undefined : json['footer_text'],
        'hideInvoicepdfsBranding': json['hide_invoicepdfs_branding'] == null ? undefined : json['hide_invoicepdfs_branding'],
    };
}

export function BrandingUpdateRequestToJSON(value?: BrandingUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'primary_color': value['primaryColor'],
        'accent_color': value['accentColor'],
        'font_family': value['fontFamily'],
        'footer_text': value['footerText'],
        'hide_invoicepdfs_branding': value['hideInvoicepdfsBranding'],
    };
}

