/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
} from './PostalAddress';

/**
 * 
 * @export
 * @interface BusinessProfilePatch
 */
export interface BusinessProfilePatch {
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    legalName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    phone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    taxId?: string | null;
    /**
     * 
     * @type {PostalAddress}
     * @memberof BusinessProfilePatch
     */
    address?: PostalAddress | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    defaultCurrency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    defaultLocale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    defaultTimezone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BusinessProfilePatch
     */
    logoFileId?: string | null;
}

/**
 * Check if a given object implements the BusinessProfilePatch interface.
 */
export function instanceOfBusinessProfilePatch(value: object): value is BusinessProfilePatch {
    return true;
}

export function BusinessProfilePatchFromJSON(json: any): BusinessProfilePatch {
    return BusinessProfilePatchFromJSONTyped(json, false);
}

export function BusinessProfilePatchFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessProfilePatch {
    if (json == null) {
        return json;
    }
    return {
        
        'legalName': json['legal_name'] == null ? undefined : json['legal_name'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'website': json['website'] == null ? undefined : json['website'],
        'taxId': json['tax_id'] == null ? undefined : json['tax_id'],
        'address': json['address'] == null ? undefined : PostalAddressFromJSON(json['address']),
        'defaultCurrency': json['default_currency'] == null ? undefined : json['default_currency'],
        'defaultLocale': json['default_locale'] == null ? undefined : json['default_locale'],
        'defaultTimezone': json['default_timezone'] == null ? undefined : json['default_timezone'],
        'logoFileId': json['logo_file_id'] == null ? undefined : json['logo_file_id'],
    };
}

export function BusinessProfilePatchToJSON(value?: BusinessProfilePatch | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'legal_name': value['legalName'],
        'display_name': value['displayName'],
        'email': value['email'],
        'phone': value['phone'],
        'website': value['website'],
        'tax_id': value['taxId'],
        'address': PostalAddressToJSON(value['address']),
        'default_currency': value['defaultCurrency'],
        'default_locale': value['defaultLocale'],
        'default_timezone': value['defaultTimezone'],
        'logo_file_id': value['logoFileId'],
    };
}

