/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessProfileOut } from './BusinessProfileOut';
import {
    BusinessProfileOutFromJSON,
    BusinessProfileOutFromJSONTyped,
    BusinessProfileOutToJSON,
} from './BusinessProfileOut';

/**
 * 
 * @export
 * @interface BusinessProfileResponse
 */
export interface BusinessProfileResponse {
    /**
     * 
     * @type {BusinessProfileOut}
     * @memberof BusinessProfileResponse
     */
    data: BusinessProfileOut;
}

/**
 * Check if a given object implements the BusinessProfileResponse interface.
 */
export function instanceOfBusinessProfileResponse(value: object): value is BusinessProfileResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function BusinessProfileResponseFromJSON(json: any): BusinessProfileResponse {
    return BusinessProfileResponseFromJSONTyped(json, false);
}

export function BusinessProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessProfileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': BusinessProfileOutFromJSON(json['data']),
    };
}

export function BusinessProfileResponseToJSON(value?: BusinessProfileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': BusinessProfileOutToJSON(value['data']),
    };
}

