/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ComplianceViolationOut
 */
export interface ComplianceViolationOut {
    /**
     * The identifier the standard uses — a business term from the mandatory-field check, a rule id from Schematron. A rule id is what a rejection notice from an access point quotes.
     * @type {string}
     * @memberof ComplianceViolationOut
     */
    rule: string;
    /**
     * Where the problem is. The mandatory-field check names a field of the request; Schematron names the node in the generated XML.
     * @type {string}
     * @memberof ComplianceViolationOut
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof ComplianceViolationOut
     */
    message: string;
    /**
     * `fatal` would get the document rejected. `warning` is a recommendation — both EN 16931 and Peppol grade a large share of their rules as advisory, and `valid` ignores those.
     * @type {string}
     * @memberof ComplianceViolationOut
     */
    severity?: string;
    /**
     * Which ruleset found it — matches an `id` in `rulesets`.
     * @type {string}
     * @memberof ComplianceViolationOut
     */
    ruleset?: string;
}

/**
 * Check if a given object implements the ComplianceViolationOut interface.
 */
export function instanceOfComplianceViolationOut(value: object): value is ComplianceViolationOut {
    if (!('rule' in value) || value['rule'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function ComplianceViolationOutFromJSON(json: any): ComplianceViolationOut {
    return ComplianceViolationOutFromJSONTyped(json, false);
}

export function ComplianceViolationOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceViolationOut {
    if (json == null) {
        return json;
    }
    return {
        
        'rule': json['rule'],
        'path': json['path'],
        'message': json['message'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'ruleset': json['ruleset'] == null ? undefined : json['ruleset'],
    };
}

export function ComplianceViolationOutToJSON(value?: ComplianceViolationOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'rule': value['rule'],
        'path': value['path'],
        'message': value['message'],
        'severity': value['severity'],
        'ruleset': value['ruleset'],
    };
}

