/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplianceViolationOut } from './ComplianceViolationOut';
import {
    ComplianceViolationOutFromJSON,
    ComplianceViolationOutFromJSONTyped,
    ComplianceViolationOutToJSON,
} from './ComplianceViolationOut';

/**
 * 
 * @export
 * @interface ComplianceCheckOut
 */
export interface ComplianceCheckOut {
    /**
     * 
     * @type {string}
     * @memberof ComplianceCheckOut
     */
    profile: string;
    /**
     * The version these rules came from. Worth recording alongside any document you file — rulesets revise, and 'which rules did this pass?' is what an audit asks years later.
     * @type {string}
     * @memberof ComplianceCheckOut
     */
    rulesetVersion: string;
    /**
     * 
     * @type {boolean}
     * @memberof ComplianceCheckOut
     */
    valid: boolean;
    /**
     * Every violation found, not the first — fixing one field per round trip is the experience this avoids.
     * @type {Array<ComplianceViolationOut>}
     * @memberof ComplianceCheckOut
     */
    violations?: Array<ComplianceViolationOut>;
}

/**
 * Check if a given object implements the ComplianceCheckOut interface.
 */
export function instanceOfComplianceCheckOut(value: object): value is ComplianceCheckOut {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('rulesetVersion' in value) || value['rulesetVersion'] === undefined) return false;
    if (!('valid' in value) || value['valid'] === undefined) return false;
    return true;
}

export function ComplianceCheckOutFromJSON(json: any): ComplianceCheckOut {
    return ComplianceCheckOutFromJSONTyped(json, false);
}

export function ComplianceCheckOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): ComplianceCheckOut {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'],
        'rulesetVersion': json['ruleset_version'],
        'valid': json['valid'],
        'violations': json['violations'] == null ? undefined : ((json['violations'] as Array<any>).map(ComplianceViolationOutFromJSON)),
    };
}

export function ComplianceCheckOutToJSON(value?: ComplianceCheckOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'profile': value['profile'],
        'ruleset_version': value['rulesetVersion'],
        'valid': value['valid'],
        'violations': value['violations'] == null ? undefined : ((value['violations'] as Array<any>).map(ComplianceViolationOutToJSON)),
    };
}

