/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditNoteLineItemInput } from './CreditNoteLineItemInput';
import {
    CreditNoteLineItemInputFromJSON,
    CreditNoteLineItemInputFromJSONTyped,
    CreditNoteLineItemInputToJSON,
} from './CreditNoteLineItemInput';

/**
 * 
 * @export
 * @interface CreditNoteCreateRequest
 */
export interface CreditNoteCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof CreditNoteCreateRequest
     */
    invoiceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteCreateRequest
     */
    creditNoteNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof CreditNoteCreateRequest
     */
    issueDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteCreateRequest
     */
    reason?: string | null;
    /**
     * 
     * @type {Array<CreditNoteLineItemInput>}
     * @memberof CreditNoteCreateRequest
     */
    lineItems: Array<CreditNoteLineItemInput>;
}

/**
 * Check if a given object implements the CreditNoteCreateRequest interface.
 */
export function instanceOfCreditNoteCreateRequest(value: object): value is CreditNoteCreateRequest {
    if (!('invoiceId' in value) || value['invoiceId'] === undefined) return false;
    if (!('creditNoteNumber' in value) || value['creditNoteNumber'] === undefined) return false;
    if (!('issueDate' in value) || value['issueDate'] === undefined) return false;
    if (!('lineItems' in value) || value['lineItems'] === undefined) return false;
    return true;
}

export function CreditNoteCreateRequestFromJSON(json: any): CreditNoteCreateRequest {
    return CreditNoteCreateRequestFromJSONTyped(json, false);
}

export function CreditNoteCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditNoteCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceId': json['invoice_id'],
        'creditNoteNumber': json['credit_note_number'],
        'issueDate': (new Date(json['issue_date'])),
        'reason': json['reason'] == null ? undefined : json['reason'],
        'lineItems': ((json['line_items'] as Array<any>).map(CreditNoteLineItemInputFromJSON)),
    };
}

export function CreditNoteCreateRequestToJSON(value?: CreditNoteCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoice_id': value['invoiceId'],
        'credit_note_number': value['creditNoteNumber'],
        'issue_date': ((value['issueDate']).toISOString().substring(0,10)),
        'reason': value['reason'],
        'line_items': ((value['lineItems'] as Array<any>).map(CreditNoteLineItemInputToJSON)),
    };
}

