/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreditNoteOut } from './CreditNoteOut';
import {
    CreditNoteOutFromJSON,
    CreditNoteOutFromJSONTyped,
    CreditNoteOutToJSON,
} from './CreditNoteOut';

/**
 * 
 * @export
 * @interface CreditNoteResponse
 */
export interface CreditNoteResponse {
    /**
     * 
     * @type {CreditNoteOut}
     * @memberof CreditNoteResponse
     */
    data: CreditNoteOut;
}

/**
 * Check if a given object implements the CreditNoteResponse interface.
 */
export function instanceOfCreditNoteResponse(value: object): value is CreditNoteResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CreditNoteResponseFromJSON(json: any): CreditNoteResponse {
    return CreditNoteResponseFromJSONTyped(json, false);
}

export function CreditNoteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditNoteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CreditNoteOutFromJSON(json['data']),
    };
}

export function CreditNoteResponseToJSON(value?: CreditNoteResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': CreditNoteOutToJSON(value['data']),
    };
}

