/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerOut } from './CustomerOut';
import {
    CustomerOutFromJSON,
    CustomerOutFromJSONTyped,
    CustomerOutToJSON,
} from './CustomerOut';

/**
 * 
 * @export
 * @interface CustomerResponse
 */
export interface CustomerResponse {
    /**
     * 
     * @type {CustomerOut}
     * @memberof CustomerResponse
     */
    data: CustomerOut;
}

/**
 * Check if a given object implements the CustomerResponse interface.
 */
export function instanceOfCustomerResponse(value: object): value is CustomerResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CustomerResponseFromJSON(json: any): CustomerResponse {
    return CustomerResponseFromJSONTyped(json, false);
}

export function CustomerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CustomerOutFromJSON(json['data']),
    };
}

export function CustomerResponseToJSON(value?: CustomerResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': CustomerOutToJSON(value['data']),
    };
}

