/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomTemplateOut } from './CustomTemplateOut';
import {
    CustomTemplateOutFromJSON,
    CustomTemplateOutFromJSONTyped,
    CustomTemplateOutToJSON,
} from './CustomTemplateOut';

/**
 * 
 * @export
 * @interface CustomTemplateResponse
 */
export interface CustomTemplateResponse {
    /**
     * 
     * @type {CustomTemplateOut}
     * @memberof CustomTemplateResponse
     */
    data: CustomTemplateOut;
}

/**
 * Check if a given object implements the CustomTemplateResponse interface.
 */
export function instanceOfCustomTemplateResponse(value: object): value is CustomTemplateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function CustomTemplateResponseFromJSON(json: any): CustomTemplateResponse {
    return CustomTemplateResponseFromJSONTyped(json, false);
}

export function CustomTemplateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomTemplateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': CustomTemplateOutFromJSON(json['data']),
    };
}

export function CustomTemplateResponseToJSON(value?: CustomTemplateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': CustomTemplateOutToJSON(value['data']),
    };
}

