/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeliveryOut } from './DeliveryOut';
import {
    DeliveryOutFromJSON,
    DeliveryOutFromJSONTyped,
    DeliveryOutToJSON,
} from './DeliveryOut';

/**
 * 
 * @export
 * @interface DeliveryResponse
 */
export interface DeliveryResponse {
    /**
     * 
     * @type {DeliveryOut}
     * @memberof DeliveryResponse
     */
    data: DeliveryOut;
}

/**
 * Check if a given object implements the DeliveryResponse interface.
 */
export function instanceOfDeliveryResponse(value: object): value is DeliveryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DeliveryResponseFromJSON(json: any): DeliveryResponse {
    return DeliveryResponseFromJSONTyped(json, false);
}

export function DeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeliveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': DeliveryOutFromJSON(json['data']),
    };
}

export function DeliveryResponseToJSON(value?: DeliveryResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': DeliveryOutToJSON(value['data']),
    };
}

