/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentTemplateRef
 */
export interface DocumentTemplateRef {
    /**
     * 
     * @type {string}
     * @memberof DocumentTemplateRef
     */
    id: string;
}

/**
 * Check if a given object implements the DocumentTemplateRef interface.
 */
export function instanceOfDocumentTemplateRef(value: object): value is DocumentTemplateRef {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function DocumentTemplateRefFromJSON(json: any): DocumentTemplateRef {
    return DocumentTemplateRefFromJSONTyped(json, false);
}

export function DocumentTemplateRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTemplateRef {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function DocumentTemplateRefToJSON(value?: DocumentTemplateRef | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

