/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
} from './PostalAddress';
import type { LineItemDiscountInput } from './LineItemDiscountInput';
import {
    LineItemDiscountInputFromJSON,
    LineItemDiscountInputFromJSONTyped,
    LineItemDiscountInputToJSON,
} from './LineItemDiscountInput';
import type { InvoiceShippingInput } from './InvoiceShippingInput';
import {
    InvoiceShippingInputFromJSON,
    InvoiceShippingInputFromJSONTyped,
    InvoiceShippingInputToJSON,
} from './InvoiceShippingInput';
import type { InvoiceNoteInput } from './InvoiceNoteInput';
import {
    InvoiceNoteInputFromJSON,
    InvoiceNoteInputFromJSONTyped,
    InvoiceNoteInputToJSON,
} from './InvoiceNoteInput';
import type { InvoicePaymentInput } from './InvoicePaymentInput';
import {
    InvoicePaymentInputFromJSON,
    InvoicePaymentInputFromJSONTyped,
    InvoicePaymentInputToJSON,
} from './InvoicePaymentInput';
import type { InvoiceBrandingInput } from './InvoiceBrandingInput';
import {
    InvoiceBrandingInputFromJSON,
    InvoiceBrandingInputFromJSONTyped,
    InvoiceBrandingInputToJSON,
} from './InvoiceBrandingInput';
import type { StandardLineItemInput } from './StandardLineItemInput';
import {
    StandardLineItemInputFromJSON,
    StandardLineItemInputFromJSONTyped,
    StandardLineItemInputToJSON,
} from './StandardLineItemInput';
import type { InvoiceTermInput } from './InvoiceTermInput';
import {
    InvoiceTermInputFromJSON,
    InvoiceTermInputFromJSONTyped,
    InvoiceTermInputToJSON,
} from './InvoiceTermInput';
import type { InvoiceCustomFieldInput } from './InvoiceCustomFieldInput';
import {
    InvoiceCustomFieldInputFromJSON,
    InvoiceCustomFieldInputFromJSONTyped,
    InvoiceCustomFieldInputToJSON,
} from './InvoiceCustomFieldInput';

/**
 * 
 * @export
 * @interface DocumentPatchRequest
 */
export interface DocumentPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    documentType?: DocumentPatchRequestDocumentTypeEnum | null;
    /**
     * 
     * @type {Date}
     * @memberof DocumentPatchRequest
     */
    issueDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DocumentPatchRequest
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    currency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    businessProfileId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    customerId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    sourceDocumentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentPatchRequest
     */
    reason?: string | null;
    /**
     * 
     * @type {PostalAddress}
     * @memberof DocumentPatchRequest
     */
    shipTo?: PostalAddress | null;
    /**
     * 
     * @type {Array<StandardLineItemInput>}
     * @memberof DocumentPatchRequest
     */
    lineItems?: Array<StandardLineItemInput> | null;
    /**
     * 
     * @type {Array<LineItemDiscountInput>}
     * @memberof DocumentPatchRequest
     */
    discounts?: Array<LineItemDiscountInput> | null;
    /**
     * 
     * @type {InvoiceShippingInput}
     * @memberof DocumentPatchRequest
     */
    shipping?: InvoiceShippingInput | null;
    /**
     * 
     * @type {Array<InvoiceNoteInput>}
     * @memberof DocumentPatchRequest
     */
    notes?: Array<InvoiceNoteInput> | null;
    /**
     * 
     * @type {Array<InvoiceTermInput>}
     * @memberof DocumentPatchRequest
     */
    terms?: Array<InvoiceTermInput> | null;
    /**
     * 
     * @type {Array<InvoiceCustomFieldInput>}
     * @memberof DocumentPatchRequest
     */
    customFields?: Array<InvoiceCustomFieldInput> | null;
    /**
     * 
     * @type {InvoicePaymentInput}
     * @memberof DocumentPatchRequest
     */
    payment?: InvoicePaymentInput | null;
    /**
     * 
     * @type {InvoiceBrandingInput}
     * @memberof DocumentPatchRequest
     */
    branding?: InvoiceBrandingInput | null;
}


/**
 * @export
 */
export const DocumentPatchRequestDocumentTypeEnum = {
    Invoice: 'invoice',
    CreditNote: 'credit_note',
    Quote: 'quote',
    Receipt: 'receipt',
    Proforma: 'proforma',
    PurchaseOrder: 'purchase_order',
    DeliveryNote: 'delivery_note'
} as const;
export type DocumentPatchRequestDocumentTypeEnum = typeof DocumentPatchRequestDocumentTypeEnum[keyof typeof DocumentPatchRequestDocumentTypeEnum];


/**
 * Check if a given object implements the DocumentPatchRequest interface.
 */
export function instanceOfDocumentPatchRequest(value: object): value is DocumentPatchRequest {
    return true;
}

export function DocumentPatchRequestFromJSON(json: any): DocumentPatchRequest {
    return DocumentPatchRequestFromJSONTyped(json, false);
}

export function DocumentPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'] == null ? undefined : json['number'],
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'issueDate': json['issue_date'] == null ? undefined : (new Date(json['issue_date'])),
        'dueDate': json['due_date'] == null ? undefined : (new Date(json['due_date'])),
        'currency': json['currency'] == null ? undefined : json['currency'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'businessProfileId': json['business_profile_id'] == null ? undefined : json['business_profile_id'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'sourceDocumentId': json['source_document_id'] == null ? undefined : json['source_document_id'],
        'reason': json['reason'] == null ? undefined : json['reason'],
        'shipTo': json['ship_to'] == null ? undefined : PostalAddressFromJSON(json['ship_to']),
        'lineItems': json['line_items'] == null ? undefined : ((json['line_items'] as Array<any>).map(StandardLineItemInputFromJSON)),
        'discounts': json['discounts'] == null ? undefined : ((json['discounts'] as Array<any>).map(LineItemDiscountInputFromJSON)),
        'shipping': json['shipping'] == null ? undefined : InvoiceShippingInputFromJSON(json['shipping']),
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(InvoiceNoteInputFromJSON)),
        'terms': json['terms'] == null ? undefined : ((json['terms'] as Array<any>).map(InvoiceTermInputFromJSON)),
        'customFields': json['custom_fields'] == null ? undefined : ((json['custom_fields'] as Array<any>).map(InvoiceCustomFieldInputFromJSON)),
        'payment': json['payment'] == null ? undefined : InvoicePaymentInputFromJSON(json['payment']),
        'branding': json['branding'] == null ? undefined : InvoiceBrandingInputFromJSON(json['branding']),
    };
}

export function DocumentPatchRequestToJSON(value?: DocumentPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'number': value['number'],
        'document_type': value['documentType'],
        'issue_date': value['issueDate'] == null ? undefined : ((value['issueDate'] as any).toISOString().substring(0,10)),
        'due_date': value['dueDate'] == null ? undefined : ((value['dueDate'] as any).toISOString().substring(0,10)),
        'currency': value['currency'],
        'locale': value['locale'],
        'business_profile_id': value['businessProfileId'],
        'customer_id': value['customerId'],
        'source_document_id': value['sourceDocumentId'],
        'reason': value['reason'],
        'ship_to': PostalAddressToJSON(value['shipTo']),
        'line_items': value['lineItems'] == null ? undefined : ((value['lineItems'] as Array<any>).map(StandardLineItemInputToJSON)),
        'discounts': value['discounts'] == null ? undefined : ((value['discounts'] as Array<any>).map(LineItemDiscountInputToJSON)),
        'shipping': InvoiceShippingInputToJSON(value['shipping']),
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(InvoiceNoteInputToJSON)),
        'terms': value['terms'] == null ? undefined : ((value['terms'] as Array<any>).map(InvoiceTermInputToJSON)),
        'custom_fields': value['customFields'] == null ? undefined : ((value['customFields'] as Array<any>).map(InvoiceCustomFieldInputToJSON)),
        'payment': InvoicePaymentInputToJSON(value['payment']),
        'branding': InvoiceBrandingInputToJSON(value['branding']),
    };
}

