/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentValidateResponse
 */
export interface DocumentValidateResponse {
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof DocumentValidateResponse
     */
    data: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the DocumentValidateResponse interface.
 */
export function instanceOfDocumentValidateResponse(value: object): value is DocumentValidateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DocumentValidateResponseFromJSON(json: any): DocumentValidateResponse {
    return DocumentValidateResponseFromJSONTyped(json, false);
}

export function DocumentValidateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentValidateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function DocumentValidateResponseToJSON(value?: DocumentValidateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
    };
}

