/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentTemplateRef } from './DocumentTemplateRef';
import {
    DocumentTemplateRefFromJSON,
    DocumentTemplateRefFromJSONTyped,
    DocumentTemplateRefToJSON,
} from './DocumentTemplateRef';
import type { DocumentOutputOptions } from './DocumentOutputOptions';
import {
    DocumentOutputOptionsFromJSON,
    DocumentOutputOptionsFromJSONTyped,
    DocumentOutputOptionsToJSON,
} from './DocumentOutputOptions';
import type { DocumentInvoiceDataInput } from './DocumentInvoiceDataInput';
import {
    DocumentInvoiceDataInputFromJSON,
    DocumentInvoiceDataInputFromJSONTyped,
    DocumentInvoiceDataInputToJSON,
} from './DocumentInvoiceDataInput';

/**
 * 
 * @export
 * @interface DocumentRenderRequest
 */
export interface DocumentRenderRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentRenderRequest
     */
    documentType?: DocumentRenderRequestDocumentTypeEnum;
    /**
     * 
     * @type {DocumentInvoiceDataInput}
     * @memberof DocumentRenderRequest
     */
    data: DocumentInvoiceDataInput;
    /**
     * 
     * @type {DocumentTemplateRef}
     * @memberof DocumentRenderRequest
     */
    template: DocumentTemplateRef;
    /**
     * 
     * @type {DocumentOutputOptions}
     * @memberof DocumentRenderRequest
     */
    output?: DocumentOutputOptions;
}


/**
 * @export
 */
export const DocumentRenderRequestDocumentTypeEnum = {
    Invoice: 'invoice'
} as const;
export type DocumentRenderRequestDocumentTypeEnum = typeof DocumentRenderRequestDocumentTypeEnum[keyof typeof DocumentRenderRequestDocumentTypeEnum];


/**
 * Check if a given object implements the DocumentRenderRequest interface.
 */
export function instanceOfDocumentRenderRequest(value: object): value is DocumentRenderRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('template' in value) || value['template'] === undefined) return false;
    return true;
}

export function DocumentRenderRequestFromJSON(json: any): DocumentRenderRequest {
    return DocumentRenderRequestFromJSONTyped(json, false);
}

export function DocumentRenderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRenderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'data': DocumentInvoiceDataInputFromJSON(json['data']),
        'template': DocumentTemplateRefFromJSON(json['template']),
        'output': json['output'] == null ? undefined : DocumentOutputOptionsFromJSON(json['output']),
    };
}

export function DocumentRenderRequestToJSON(value?: DocumentRenderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'document_type': value['documentType'],
        'data': DocumentInvoiceDataInputToJSON(value['data']),
        'template': DocumentTemplateRefToJSON(value['template']),
        'output': DocumentOutputOptionsToJSON(value['output']),
    };
}

