/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentInvoiceDataInput } from './DocumentInvoiceDataInput';
import {
    DocumentInvoiceDataInputFromJSON,
    DocumentInvoiceDataInputFromJSONTyped,
    DocumentInvoiceDataInputToJSON,
} from './DocumentInvoiceDataInput';

/**
 * 
 * @export
 * @interface DocumentComplianceRequest
 */
export interface DocumentComplianceRequest {
    /**
     * 
     * @type {string}
     * @memberof DocumentComplianceRequest
     */
    documentType?: DocumentComplianceRequestDocumentTypeEnum;
    /**
     * 
     * @type {DocumentInvoiceDataInput}
     * @memberof DocumentComplianceRequest
     */
    data: DocumentInvoiceDataInput;
    /**
     * Which ruleset to hold the document to. Rulesets differ: a document valid under one can be rejected by another, so there is no default.
     * @type {string}
     * @memberof DocumentComplianceRequest
     */
    profile: string;
}


/**
 * @export
 */
export const DocumentComplianceRequestDocumentTypeEnum = {
    Invoice: 'invoice',
    CreditNote: 'credit_note',
    DebitNote: 'debit_note',
    Quote: 'quote',
    Receipt: 'receipt',
    Proforma: 'proforma',
    PurchaseOrder: 'purchase_order',
    DeliveryNote: 'delivery_note'
} as const;
export type DocumentComplianceRequestDocumentTypeEnum = typeof DocumentComplianceRequestDocumentTypeEnum[keyof typeof DocumentComplianceRequestDocumentTypeEnum];


/**
 * Check if a given object implements the DocumentComplianceRequest interface.
 */
export function instanceOfDocumentComplianceRequest(value: object): value is DocumentComplianceRequest {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function DocumentComplianceRequestFromJSON(json: any): DocumentComplianceRequest {
    return DocumentComplianceRequestFromJSONTyped(json, false);
}

export function DocumentComplianceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentComplianceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'data': DocumentInvoiceDataInputFromJSON(json['data']),
        'profile': json['profile'],
    };
}

export function DocumentComplianceRequestToJSON(value?: DocumentComplianceRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'document_type': value['documentType'],
        'data': DocumentInvoiceDataInputToJSON(value['data']),
        'profile': value['profile'],
    };
}

