/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The document lifecycle.
 * @export
 */
export const DocumentStatus = {
    Draft: 'draft',
    Finalized: 'finalized',
    Sent: 'sent',
    Paid: 'paid',
    Void: 'void',
    Archived: 'archived'
} as const;
export type DocumentStatus = typeof DocumentStatus[keyof typeof DocumentStatus];


export function instanceOfDocumentStatus(value: any): boolean {
    for (const key in DocumentStatus) {
        if (Object.prototype.hasOwnProperty.call(DocumentStatus, key)) {
            if ((DocumentStatus as Record<string, DocumentStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DocumentStatusFromJSON(json: any): DocumentStatus {
    return DocumentStatusFromJSONTyped(json, false);
}

export function DocumentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentStatus {
    return json as DocumentStatus;
}

export function DocumentStatusToJSON(value?: DocumentStatus | null): any {
    return value as any;
}

