/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentCustomFieldInput
 */
export interface DocumentCustomFieldInput {
    /**
     * 
     * @type {string}
     * @memberof DocumentCustomFieldInput
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentCustomFieldInput
     */
    value: string;
}

/**
 * Check if a given object implements the DocumentCustomFieldInput interface.
 */
export function instanceOfDocumentCustomFieldInput(value: object): value is DocumentCustomFieldInput {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DocumentCustomFieldInputFromJSON(json: any): DocumentCustomFieldInput {
    return DocumentCustomFieldInputFromJSONTyped(json, false);
}

export function DocumentCustomFieldInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentCustomFieldInput {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'value': json['value'],
    };
}

export function DocumentCustomFieldInputToJSON(value?: DocumentCustomFieldInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'label': value['label'],
        'value': value['value'],
    };
}

