/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentDiscountInput
 */
export interface DocumentDiscountInput {
    /**
     * 
     * @type {string}
     * @memberof DocumentDiscountInput
     */
    type?: DocumentDiscountInputTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DocumentDiscountInput
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentDiscountInput
     */
    reason?: string | null;
}


/**
 * @export
 */
export const DocumentDiscountInputTypeEnum = {
    Percentage: 'percentage',
    Fixed: 'fixed'
} as const;
export type DocumentDiscountInputTypeEnum = typeof DocumentDiscountInputTypeEnum[keyof typeof DocumentDiscountInputTypeEnum];


/**
 * Check if a given object implements the DocumentDiscountInput interface.
 */
export function instanceOfDocumentDiscountInput(value: object): value is DocumentDiscountInput {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DocumentDiscountInputFromJSON(json: any): DocumentDiscountInput {
    return DocumentDiscountInputFromJSONTyped(json, false);
}

export function DocumentDiscountInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentDiscountInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function DocumentDiscountInputToJSON(value?: DocumentDiscountInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
        'reason': value['reason'],
    };
}

