/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Render options for an already-stored document (``POST /documents/{id}/renders``).
 * 
 * Distinct from ``app.schemas.v1.DocumentRenderRequest``, which carries a full inline
 * document for the stateless ``POST /documents/render``. Two classes sharing one name
 * made FastAPI fall back to module-qualified schema names in the spec
 * (``app__documents__schemas__DocumentRenderRequest``), which the SDK generators turned
 * into ``AppDocumentsSchemasDocumentRenderRequest``.
 * @export
 * @interface DocumentRenderOptions
 */
export interface DocumentRenderOptions {
    /**
     * 
     * @type {string}
     * @memberof DocumentRenderOptions
     */
    templateId?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentRenderOptions
     */
    templateVersion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DocumentRenderOptions
     */
    pageSize?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentRenderOptions
     */
    expiresIn?: number;
    /**
     * `facturx_pdf` embeds the EN 16931 CII XML in a PDF/A-3, which is what a French or German counterparty means by Factur-X or ZUGFeRD.
     * @type {string}
     * @memberof DocumentRenderOptions
     */
    format?: DocumentRenderOptionsFormatEnum;
}


/**
 * @export
 */
export const DocumentRenderOptionsFormatEnum = {
    Pdf: 'pdf',
    FacturxPdf: 'facturx_pdf'
} as const;
export type DocumentRenderOptionsFormatEnum = typeof DocumentRenderOptionsFormatEnum[keyof typeof DocumentRenderOptionsFormatEnum];


/**
 * Check if a given object implements the DocumentRenderOptions interface.
 */
export function instanceOfDocumentRenderOptions(value: object): value is DocumentRenderOptions {
    return true;
}

export function DocumentRenderOptionsFromJSON(json: any): DocumentRenderOptions {
    return DocumentRenderOptionsFromJSONTyped(json, false);
}

export function DocumentRenderOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRenderOptions {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'] == null ? undefined : json['template_id'],
        'templateVersion': json['template_version'] == null ? undefined : json['template_version'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'format': json['format'] == null ? undefined : json['format'],
    };
}

export function DocumentRenderOptionsToJSON(value?: DocumentRenderOptions | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'template_id': value['templateId'],
        'template_version': value['templateVersion'],
        'page_size': value['pageSize'],
        'expires_in': value['expiresIn'],
        'format': value['format'],
    };
}

