/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentLineItemTaxInput
 */
export interface DocumentLineItemTaxInput {
    /**
     * 
     * @type {string}
     * @memberof DocumentLineItemTaxInput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentLineItemTaxInput
     */
    rate: string;
    /**
     * 
     * @type {boolean}
     * @memberof DocumentLineItemTaxInput
     */
    inclusive?: boolean;
}

/**
 * Check if a given object implements the DocumentLineItemTaxInput interface.
 */
export function instanceOfDocumentLineItemTaxInput(value: object): value is DocumentLineItemTaxInput {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    return true;
}

export function DocumentLineItemTaxInputFromJSON(json: any): DocumentLineItemTaxInput {
    return DocumentLineItemTaxInputFromJSONTyped(json, false);
}

export function DocumentLineItemTaxInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentLineItemTaxInput {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rate': json['rate'],
        'inclusive': json['inclusive'] == null ? undefined : json['inclusive'],
    };
}

export function DocumentLineItemTaxInputToJSON(value?: DocumentLineItemTaxInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'rate': value['rate'],
        'inclusive': value['inclusive'],
    };
}

