/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportOut } from './ImportOut';
import {
    ImportOutFromJSON,
    ImportOutFromJSONTyped,
    ImportOutToJSON,
} from './ImportOut';

/**
 * 
 * @export
 * @interface ImportResponse
 */
export interface ImportResponse {
    /**
     * 
     * @type {ImportOut}
     * @memberof ImportResponse
     */
    data: ImportOut;
}

/**
 * Check if a given object implements the ImportResponse interface.
 */
export function instanceOfImportResponse(value: object): value is ImportResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function ImportResponseFromJSON(json: any): ImportResponse {
    return ImportResponseFromJSONTyped(json, false);
}

export function ImportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ImportOutFromJSON(json['data']),
    };
}

export function ImportResponseToJSON(value?: ImportResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ImportOutToJSON(value['data']),
    };
}

