/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MoneyOut } from './MoneyOut';
import {
    MoneyOutFromJSON,
    MoneyOutFromJSONTyped,
    MoneyOutToJSON,
} from './MoneyOut';

/**
 * 
 * @export
 * @interface InvoiceTotalsOut
 */
export interface InvoiceTotalsOut {
    /**
     * 
     * @type {MoneyOut}
     * @memberof InvoiceTotalsOut
     */
    subtotal: MoneyOut;
    /**
     * 
     * @type {MoneyOut}
     * @memberof InvoiceTotalsOut
     */
    discountTotal: MoneyOut;
    /**
     * 
     * @type {MoneyOut}
     * @memberof InvoiceTotalsOut
     */
    taxTotal: MoneyOut;
    /**
     * 
     * @type {MoneyOut}
     * @memberof InvoiceTotalsOut
     */
    shippingTotal: MoneyOut;
    /**
     * 
     * @type {MoneyOut}
     * @memberof InvoiceTotalsOut
     */
    total: MoneyOut;
}

/**
 * Check if a given object implements the InvoiceTotalsOut interface.
 */
export function instanceOfInvoiceTotalsOut(value: object): value is InvoiceTotalsOut {
    if (!('subtotal' in value) || value['subtotal'] === undefined) return false;
    if (!('discountTotal' in value) || value['discountTotal'] === undefined) return false;
    if (!('taxTotal' in value) || value['taxTotal'] === undefined) return false;
    if (!('shippingTotal' in value) || value['shippingTotal'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function InvoiceTotalsOutFromJSON(json: any): InvoiceTotalsOut {
    return InvoiceTotalsOutFromJSONTyped(json, false);
}

export function InvoiceTotalsOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceTotalsOut {
    if (json == null) {
        return json;
    }
    return {
        
        'subtotal': MoneyOutFromJSON(json['subtotal']),
        'discountTotal': MoneyOutFromJSON(json['discount_total']),
        'taxTotal': MoneyOutFromJSON(json['tax_total']),
        'shippingTotal': MoneyOutFromJSON(json['shipping_total']),
        'total': MoneyOutFromJSON(json['total']),
    };
}

export function InvoiceTotalsOutToJSON(value?: InvoiceTotalsOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'subtotal': MoneyOutToJSON(value['subtotal']),
        'discount_total': MoneyOutToJSON(value['discountTotal']),
        'tax_total': MoneyOutToJSON(value['taxTotal']),
        'shipping_total': MoneyOutToJSON(value['shippingTotal']),
        'total': MoneyOutToJSON(value['total']),
    };
}

