/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceShippingInput
 */
export interface InvoiceShippingInput {
    /**
     * 
     * @type {string}
     * @memberof InvoiceShippingInput
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceShippingInput
     */
    amount: string;
}

/**
 * Check if a given object implements the InvoiceShippingInput interface.
 */
export function instanceOfInvoiceShippingInput(value: object): value is InvoiceShippingInput {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function InvoiceShippingInputFromJSON(json: any): InvoiceShippingInput {
    return InvoiceShippingInputFromJSONTyped(json, false);
}

export function InvoiceShippingInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceShippingInput {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'amount': json['amount'],
    };
}

export function InvoiceShippingInputToJSON(value?: InvoiceShippingInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'amount': value['amount'],
    };
}

