/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceBankAccountInput } from './InvoiceBankAccountInput';
import {
    InvoiceBankAccountInputFromJSON,
    InvoiceBankAccountInputFromJSONTyped,
    InvoiceBankAccountInputToJSON,
} from './InvoiceBankAccountInput';

/**
 * 
 * @export
 * @interface InvoicePaymentInput
 */
export interface InvoicePaymentInput {
    /**
     * 
     * @type {InvoiceBankAccountInput}
     * @memberof InvoicePaymentInput
     */
    bankAccount?: InvoiceBankAccountInput | null;
    /**
     * 
     * @type {string}
     * @memberof InvoicePaymentInput
     */
    paymentUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvoicePaymentInput
     */
    acceptedMethods?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof InvoicePaymentInput
     */
    instructions?: string | null;
}

/**
 * Check if a given object implements the InvoicePaymentInput interface.
 */
export function instanceOfInvoicePaymentInput(value: object): value is InvoicePaymentInput {
    return true;
}

export function InvoicePaymentInputFromJSON(json: any): InvoicePaymentInput {
    return InvoicePaymentInputFromJSONTyped(json, false);
}

export function InvoicePaymentInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicePaymentInput {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccount': json['bank_account'] == null ? undefined : InvoiceBankAccountInputFromJSON(json['bank_account']),
        'paymentUrl': json['payment_url'] == null ? undefined : json['payment_url'],
        'acceptedMethods': json['accepted_methods'] == null ? undefined : json['accepted_methods'],
        'instructions': json['instructions'] == null ? undefined : json['instructions'],
    };
}

export function InvoicePaymentInputToJSON(value?: InvoicePaymentInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bank_account': InvoiceBankAccountInputToJSON(value['bankAccount']),
        'payment_url': value['paymentUrl'],
        'accepted_methods': value['acceptedMethods'],
        'instructions': value['instructions'],
    };
}

