/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostalAddress } from './PostalAddress';
import {
    PostalAddressFromJSON,
    PostalAddressFromJSONTyped,
    PostalAddressToJSON,
} from './PostalAddress';
import type { InvoiceShippingInput } from './InvoiceShippingInput';
import {
    InvoiceShippingInputFromJSON,
    InvoiceShippingInputFromJSONTyped,
    InvoiceShippingInputToJSON,
} from './InvoiceShippingInput';
import type { InvoiceDiscountInput } from './InvoiceDiscountInput';
import {
    InvoiceDiscountInputFromJSON,
    InvoiceDiscountInputFromJSONTyped,
    InvoiceDiscountInputToJSON,
} from './InvoiceDiscountInput';
import type { InvoiceNoteInput } from './InvoiceNoteInput';
import {
    InvoiceNoteInputFromJSON,
    InvoiceNoteInputFromJSONTyped,
    InvoiceNoteInputToJSON,
} from './InvoiceNoteInput';
import type { InvoicePaymentInput } from './InvoicePaymentInput';
import {
    InvoicePaymentInputFromJSON,
    InvoicePaymentInputFromJSONTyped,
    InvoicePaymentInputToJSON,
} from './InvoicePaymentInput';
import type { InvoiceBrandingInput } from './InvoiceBrandingInput';
import {
    InvoiceBrandingInputFromJSON,
    InvoiceBrandingInputFromJSONTyped,
    InvoiceBrandingInputToJSON,
} from './InvoiceBrandingInput';
import type { InvoiceLineItemInput } from './InvoiceLineItemInput';
import {
    InvoiceLineItemInputFromJSON,
    InvoiceLineItemInputFromJSONTyped,
    InvoiceLineItemInputToJSON,
} from './InvoiceLineItemInput';
import type { InvoiceTermInput } from './InvoiceTermInput';
import {
    InvoiceTermInputFromJSON,
    InvoiceTermInputFromJSONTyped,
    InvoiceTermInputToJSON,
} from './InvoiceTermInput';
import type { InvoiceCustomFieldInput } from './InvoiceCustomFieldInput';
import {
    InvoiceCustomFieldInputFromJSON,
    InvoiceCustomFieldInputFromJSONTyped,
    InvoiceCustomFieldInputToJSON,
} from './InvoiceCustomFieldInput';

/**
 * 
 * @export
 * @interface InvoiceDraftRequest
 */
export interface InvoiceDraftRequest {
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    invoiceNumber: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    documentType?: InvoiceDraftRequestDocumentTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceDraftRequest
     */
    issueDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceDraftRequest
     */
    dueDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    locale?: string | null;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    businessProfileId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceDraftRequest
     */
    customerId: string;
    /**
     * 
     * @type {PostalAddress}
     * @memberof InvoiceDraftRequest
     */
    shipTo?: PostalAddress | null;
    /**
     * 
     * @type {Array<InvoiceLineItemInput>}
     * @memberof InvoiceDraftRequest
     */
    lineItems: Array<InvoiceLineItemInput>;
    /**
     * 
     * @type {Array<InvoiceDiscountInput>}
     * @memberof InvoiceDraftRequest
     */
    discounts?: Array<InvoiceDiscountInput>;
    /**
     * 
     * @type {InvoiceShippingInput}
     * @memberof InvoiceDraftRequest
     */
    shipping?: InvoiceShippingInput | null;
    /**
     * 
     * @type {Array<InvoiceNoteInput>}
     * @memberof InvoiceDraftRequest
     */
    notes?: Array<InvoiceNoteInput>;
    /**
     * 
     * @type {Array<InvoiceTermInput>}
     * @memberof InvoiceDraftRequest
     */
    terms?: Array<InvoiceTermInput>;
    /**
     * 
     * @type {Array<InvoiceCustomFieldInput>}
     * @memberof InvoiceDraftRequest
     */
    customFields?: Array<InvoiceCustomFieldInput>;
    /**
     * 
     * @type {InvoicePaymentInput}
     * @memberof InvoiceDraftRequest
     */
    payment?: InvoicePaymentInput | null;
    /**
     * 
     * @type {InvoiceBrandingInput}
     * @memberof InvoiceDraftRequest
     */
    branding?: InvoiceBrandingInput | null;
}


/**
 * @export
 */
export const InvoiceDraftRequestDocumentTypeEnum = {
    Invoice: 'invoice',
    CreditNote: 'credit_note',
    Quote: 'quote',
    Receipt: 'receipt',
    Proforma: 'proforma',
    PurchaseOrder: 'purchase_order',
    DeliveryNote: 'delivery_note'
} as const;
export type InvoiceDraftRequestDocumentTypeEnum = typeof InvoiceDraftRequestDocumentTypeEnum[keyof typeof InvoiceDraftRequestDocumentTypeEnum];


/**
 * Check if a given object implements the InvoiceDraftRequest interface.
 */
export function instanceOfInvoiceDraftRequest(value: object): value is InvoiceDraftRequest {
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('issueDate' in value) || value['issueDate'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('businessProfileId' in value) || value['businessProfileId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('lineItems' in value) || value['lineItems'] === undefined) return false;
    return true;
}

export function InvoiceDraftRequestFromJSON(json: any): InvoiceDraftRequest {
    return InvoiceDraftRequestFromJSONTyped(json, false);
}

export function InvoiceDraftRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceDraftRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'invoiceNumber': json['invoice_number'],
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'issueDate': (new Date(json['issue_date'])),
        'dueDate': json['due_date'] == null ? undefined : (new Date(json['due_date'])),
        'currency': json['currency'],
        'locale': json['locale'] == null ? undefined : json['locale'],
        'businessProfileId': json['business_profile_id'],
        'customerId': json['customer_id'],
        'shipTo': json['ship_to'] == null ? undefined : PostalAddressFromJSON(json['ship_to']),
        'lineItems': ((json['line_items'] as Array<any>).map(InvoiceLineItemInputFromJSON)),
        'discounts': json['discounts'] == null ? undefined : ((json['discounts'] as Array<any>).map(InvoiceDiscountInputFromJSON)),
        'shipping': json['shipping'] == null ? undefined : InvoiceShippingInputFromJSON(json['shipping']),
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(InvoiceNoteInputFromJSON)),
        'terms': json['terms'] == null ? undefined : ((json['terms'] as Array<any>).map(InvoiceTermInputFromJSON)),
        'customFields': json['custom_fields'] == null ? undefined : ((json['custom_fields'] as Array<any>).map(InvoiceCustomFieldInputFromJSON)),
        'payment': json['payment'] == null ? undefined : InvoicePaymentInputFromJSON(json['payment']),
        'branding': json['branding'] == null ? undefined : InvoiceBrandingInputFromJSON(json['branding']),
    };
}

export function InvoiceDraftRequestToJSON(value?: InvoiceDraftRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'invoice_number': value['invoiceNumber'],
        'document_type': value['documentType'],
        'issue_date': ((value['issueDate']).toISOString().substring(0,10)),
        'due_date': value['dueDate'] == null ? undefined : ((value['dueDate'] as any).toISOString().substring(0,10)),
        'currency': value['currency'],
        'locale': value['locale'],
        'business_profile_id': value['businessProfileId'],
        'customer_id': value['customerId'],
        'ship_to': PostalAddressToJSON(value['shipTo']),
        'line_items': ((value['lineItems'] as Array<any>).map(InvoiceLineItemInputToJSON)),
        'discounts': value['discounts'] == null ? undefined : ((value['discounts'] as Array<any>).map(InvoiceDiscountInputToJSON)),
        'shipping': InvoiceShippingInputToJSON(value['shipping']),
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(InvoiceNoteInputToJSON)),
        'terms': value['terms'] == null ? undefined : ((value['terms'] as Array<any>).map(InvoiceTermInputToJSON)),
        'custom_fields': value['customFields'] == null ? undefined : ((value['customFields'] as Array<any>).map(InvoiceCustomFieldInputToJSON)),
        'payment': InvoicePaymentInputToJSON(value['payment']),
        'branding': InvoiceBrandingInputToJSON(value['branding']),
    };
}

