/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobProgressOut
 */
export interface JobProgressOut {
    /**
     * 
     * @type {number}
     * @memberof JobProgressOut
     */
    current: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgressOut
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof JobProgressOut
     */
    percentage: number;
}

/**
 * Check if a given object implements the JobProgressOut interface.
 */
export function instanceOfJobProgressOut(value: object): value is JobProgressOut {
    if (!('current' in value) || value['current'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('percentage' in value) || value['percentage'] === undefined) return false;
    return true;
}

export function JobProgressOutFromJSON(json: any): JobProgressOut {
    return JobProgressOutFromJSONTyped(json, false);
}

export function JobProgressOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobProgressOut {
    if (json == null) {
        return json;
    }
    return {
        
        'current': json['current'],
        'total': json['total'],
        'percentage': json['percentage'],
    };
}

export function JobProgressOutToJSON(value?: JobProgressOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'current': value['current'],
        'total': value['total'],
        'percentage': value['percentage'],
    };
}

