/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobOut } from './JobOut';
import {
    JobOutFromJSON,
    JobOutFromJSONTyped,
    JobOutToJSON,
} from './JobOut';

/**
 * 
 * @export
 * @interface JobResponse
 */
export interface JobResponse {
    /**
     * 
     * @type {JobOut}
     * @memberof JobResponse
     */
    data: JobOut;
}

/**
 * Check if a given object implements the JobResponse interface.
 */
export function instanceOfJobResponse(value: object): value is JobResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function JobResponseFromJSON(json: any): JobResponse {
    return JobResponseFromJSONTyped(json, false);
}

export function JobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': JobOutFromJSON(json['data']),
    };
}

export function JobResponseToJSON(value?: JobResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': JobOutToJSON(value['data']),
    };
}

