/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineItemTaxInput
 */
export interface LineItemTaxInput {
    /**
     * 
     * @type {string}
     * @memberof LineItemTaxInput
     */
    taxRateId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LineItemTaxInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LineItemTaxInput
     */
    rate?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof LineItemTaxInput
     */
    inclusive?: boolean;
}

/**
 * Check if a given object implements the LineItemTaxInput interface.
 */
export function instanceOfLineItemTaxInput(value: object): value is LineItemTaxInput {
    return true;
}

export function LineItemTaxInputFromJSON(json: any): LineItemTaxInput {
    return LineItemTaxInputFromJSONTyped(json, false);
}

export function LineItemTaxInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemTaxInput {
    if (json == null) {
        return json;
    }
    return {
        
        'taxRateId': json['tax_rate_id'] == null ? undefined : json['tax_rate_id'],
        'name': json['name'] == null ? undefined : json['name'],
        'rate': json['rate'] == null ? undefined : json['rate'],
        'inclusive': json['inclusive'] == null ? undefined : json['inclusive'],
    };
}

export function LineItemTaxInputToJSON(value?: LineItemTaxInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'tax_rate_id': value['taxRateId'],
        'name': value['name'],
        'rate': value['rate'],
        'inclusive': value['inclusive'],
    };
}

