/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LineItemDiscountInput
 */
export interface LineItemDiscountInput {
    /**
     * 
     * @type {string}
     * @memberof LineItemDiscountInput
     */
    type?: LineItemDiscountInputTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof LineItemDiscountInput
     */
    value: string;
    /**
     * 
     * @type {string}
     * @memberof LineItemDiscountInput
     */
    reason?: string | null;
}


/**
 * @export
 */
export const LineItemDiscountInputTypeEnum = {
    Percentage: 'percentage',
    Fixed: 'fixed'
} as const;
export type LineItemDiscountInputTypeEnum = typeof LineItemDiscountInputTypeEnum[keyof typeof LineItemDiscountInputTypeEnum];


/**
 * Check if a given object implements the LineItemDiscountInput interface.
 */
export function instanceOfLineItemDiscountInput(value: object): value is LineItemDiscountInput {
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function LineItemDiscountInputFromJSON(json: any): LineItemDiscountInput {
    return LineItemDiscountInputFromJSONTyped(json, false);
}

export function LineItemDiscountInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineItemDiscountInput {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'value': json['value'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function LineItemDiscountInputToJSON(value?: LineItemDiscountInput | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'value': value['value'],
        'reason': value['reason'],
    };
}

