/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LocaleOut } from './LocaleOut';
import {
    LocaleOutFromJSON,
    LocaleOutFromJSONTyped,
    LocaleOutToJSON,
} from './LocaleOut';

/**
 * 
 * @export
 * @interface LocalesListResponse
 */
export interface LocalesListResponse {
    /**
     * 
     * @type {Array<LocaleOut>}
     * @memberof LocalesListResponse
     */
    data: Array<LocaleOut>;
}

/**
 * Check if a given object implements the LocalesListResponse interface.
 */
export function instanceOfLocalesListResponse(value: object): value is LocalesListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function LocalesListResponseFromJSON(json: any): LocalesListResponse {
    return LocalesListResponseFromJSONTyped(json, false);
}

export function LocalesListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocalesListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(LocaleOutFromJSON)),
    };
}

export function LocalesListResponseToJSON(value?: LocalesListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(LocaleOutToJSON)),
    };
}

