/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What POST /numbering-sequences/{id}/next allocated.
 * 
 * The number is the point of the call. It used to answer with the sequence
 * row instead, so a caller burned a number and had to reconstruct the string
 * itself from prefix, date pattern and padding — the one thing the endpoint
 * exists to do for them.
 * @export
 * @interface NumberingNextOut
 */
export interface NumberingNextOut {
    /**
     * 
     * @type {string}
     * @memberof NumberingNextOut
     */
    number: string;
    /**
     * 
     * @type {string}
     * @memberof NumberingNextOut
     */
    sequenceId: string;
    /**
     * The counter after this allocation
     * @type {number}
     * @memberof NumberingNextOut
     */
    nextNumber: number;
}

/**
 * Check if a given object implements the NumberingNextOut interface.
 */
export function instanceOfNumberingNextOut(value: object): value is NumberingNextOut {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('sequenceId' in value) || value['sequenceId'] === undefined) return false;
    if (!('nextNumber' in value) || value['nextNumber'] === undefined) return false;
    return true;
}

export function NumberingNextOutFromJSON(json: any): NumberingNextOut {
    return NumberingNextOutFromJSONTyped(json, false);
}

export function NumberingNextOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingNextOut {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'sequenceId': json['sequence_id'],
        'nextNumber': json['next_number'],
    };
}

export function NumberingNextOutToJSON(value?: NumberingNextOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'number': value['number'],
        'sequence_id': value['sequenceId'],
        'next_number': value['nextNumber'],
    };
}

