/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NumberingSequenceOut } from './NumberingSequenceOut';
import {
    NumberingSequenceOutFromJSON,
    NumberingSequenceOutFromJSONTyped,
    NumberingSequenceOutToJSON,
} from './NumberingSequenceOut';

/**
 * 
 * @export
 * @interface NumberingSequenceResponse
 */
export interface NumberingSequenceResponse {
    /**
     * 
     * @type {NumberingSequenceOut}
     * @memberof NumberingSequenceResponse
     */
    data: NumberingSequenceOut;
}

/**
 * Check if a given object implements the NumberingSequenceResponse interface.
 */
export function instanceOfNumberingSequenceResponse(value: object): value is NumberingSequenceResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function NumberingSequenceResponseFromJSON(json: any): NumberingSequenceResponse {
    return NumberingSequenceResponseFromJSONTyped(json, false);
}

export function NumberingSequenceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberingSequenceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': NumberingSequenceOutFromJSON(json['data']),
    };
}

export function NumberingSequenceResponseToJSON(value?: NumberingSequenceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': NumberingSequenceOutToJSON(value['data']),
    };
}

