/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentOut } from './PaymentOut';
import {
    PaymentOutFromJSON,
    PaymentOutFromJSONTyped,
    PaymentOutToJSON,
} from './PaymentOut';

/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * 
     * @type {PaymentOut}
     * @memberof PaymentResponse
     */
    data: PaymentOut;
}

/**
 * Check if a given object implements the PaymentResponse interface.
 */
export function instanceOfPaymentResponse(value: object): value is PaymentResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function PaymentResponseFromJSON(json: any): PaymentResponse {
    return PaymentResponseFromJSONTyped(json, false);
}

export function PaymentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': PaymentOutFromJSON(json['data']),
    };
}

export function PaymentResponseToJSON(value?: PaymentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': PaymentOutToJSON(value['data']),
    };
}

