/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostalAddress
 */
export interface PostalAddress {
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    line1: string;
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    line2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    city?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    state?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    postalCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PostalAddress
     */
    country?: string | null;
}

/**
 * Check if a given object implements the PostalAddress interface.
 */
export function instanceOfPostalAddress(value: object): value is PostalAddress {
    if (!('line1' in value) || value['line1'] === undefined) return false;
    return true;
}

export function PostalAddressFromJSON(json: any): PostalAddress {
    return PostalAddressFromJSONTyped(json, false);
}

export function PostalAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostalAddress {
    if (json == null) {
        return json;
    }
    return {
        
        'line1': json['line1'],
        'line2': json['line2'] == null ? undefined : json['line2'],
        'city': json['city'] == null ? undefined : json['city'],
        'state': json['state'] == null ? undefined : json['state'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'country': json['country'] == null ? undefined : json['country'],
    };
}

export function PostalAddressToJSON(value?: PostalAddress | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'line1': value['line1'],
        'line2': value['line2'],
        'city': value['city'],
        'state': value['state'],
        'postal_code': value['postalCode'],
        'country': value['country'],
    };
}

