/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyResponse
 */
export interface ReadyResponse {
    /**
     * 
     * @type {string}
     * @memberof ReadyResponse
     */
    status: ReadyResponseStatusEnum;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReadyResponse
     */
    dependencies: { [key: string]: string; };
}


/**
 * @export
 */
export const ReadyResponseStatusEnum = {
    Ready: 'ready',
    NotReady: 'not_ready'
} as const;
export type ReadyResponseStatusEnum = typeof ReadyResponseStatusEnum[keyof typeof ReadyResponseStatusEnum];

/**
 * @export
 */
export const ReadyResponseDependenciesEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type ReadyResponseDependenciesEnum = typeof ReadyResponseDependenciesEnum[keyof typeof ReadyResponseDependenciesEnum];


/**
 * Check if a given object implements the ReadyResponse interface.
 */
export function instanceOfReadyResponse(value: object): value is ReadyResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('dependencies' in value) || value['dependencies'] === undefined) return false;
    return true;
}

export function ReadyResponseFromJSON(json: any): ReadyResponse {
    return ReadyResponseFromJSONTyped(json, false);
}

export function ReadyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'dependencies': json['dependencies'],
    };
}

export function ReadyResponseToJSON(value?: ReadyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'dependencies': value['dependencies'],
    };
}

