/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecurringInvoiceOut } from './RecurringInvoiceOut';
import {
    RecurringInvoiceOutFromJSON,
    RecurringInvoiceOutFromJSONTyped,
    RecurringInvoiceOutToJSON,
} from './RecurringInvoiceOut';

/**
 * 
 * @export
 * @interface RecurringInvoiceResponse
 */
export interface RecurringInvoiceResponse {
    /**
     * 
     * @type {RecurringInvoiceOut}
     * @memberof RecurringInvoiceResponse
     */
    data: RecurringInvoiceOut;
}

/**
 * Check if a given object implements the RecurringInvoiceResponse interface.
 */
export function instanceOfRecurringInvoiceResponse(value: object): value is RecurringInvoiceResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function RecurringInvoiceResponseFromJSON(json: any): RecurringInvoiceResponse {
    return RecurringInvoiceResponseFromJSONTyped(json, false);
}

export function RecurringInvoiceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringInvoiceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': RecurringInvoiceOutFromJSON(json['data']),
    };
}

export function RecurringInvoiceResponseToJSON(value?: RecurringInvoiceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': RecurringInvoiceOutToJSON(value['data']),
    };
}

