/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * `completed` is the schedule running out, not a failure — set by
 * app/recurring/processor.py when the end date or occurrence count is
 * reached. `RecurringInvoiceOut.status` was an unconstrained `str`, so this
 * is the first time the set has been written down anywhere.
 * @export
 */
export const RecurringInvoiceStatus = {
    Active: 'active',
    Paused: 'paused',
    Cancelled: 'cancelled',
    Completed: 'completed'
} as const;
export type RecurringInvoiceStatus = typeof RecurringInvoiceStatus[keyof typeof RecurringInvoiceStatus];


export function instanceOfRecurringInvoiceStatus(value: any): boolean {
    for (const key in RecurringInvoiceStatus) {
        if (Object.prototype.hasOwnProperty.call(RecurringInvoiceStatus, key)) {
            if ((RecurringInvoiceStatus as Record<string, RecurringInvoiceStatus>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RecurringInvoiceStatusFromJSON(json: any): RecurringInvoiceStatus {
    return RecurringInvoiceStatusFromJSONTyped(json, false);
}

export function RecurringInvoiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecurringInvoiceStatus {
    return json as RecurringInvoiceStatus;
}

export function RecurringInvoiceStatusToJSON(value?: RecurringInvoiceStatus | null): any {
    return value as any;
}

