/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ComplianceViolationOut } from './ComplianceViolationOut';
import {
    ComplianceViolationOutFromJSON,
    ComplianceViolationOutFromJSONTyped,
    ComplianceViolationOutToJSON,
} from './ComplianceViolationOut';

/**
 * What this PDF was held to, for a render that carries embedded XML.
 * 
 * Absent on a plain `pdf`: no ruleset was applied, so there is no claim to
 * report. A render that was produced at all satisfied every fatal rule that
 * ran — the render is refused otherwise — so the useful questions are which
 * rules those were, and whether all of them ran.
 * @export
 * @interface RenderComplianceOut
 */
export interface RenderComplianceOut {
    /**
     * The ruleset this document was built and validated against.
     * @type {string}
     * @memberof RenderComplianceOut
     */
    profile: string;
    /**
     * The artefact versions the check actually ran. A profile is held to more than one ruleset, and they are regenerated over time, so this is what makes 'which rules did this pass?' answerable later.
     * @type {string}
     * @memberof RenderComplianceOut
     */
    rulesetVersion: string;
    /**
     * False when a ruleset could not run. The document still satisfied everything that did, but the authoritative Schematron tier being absent is a materially weaker statement than it passing.
     * @type {boolean}
     * @memberof RenderComplianceOut
     */
    fullyChecked: boolean;
    /**
     * Non-fatal findings the render proceeded past. Both rulesets grade a large share of their rules as advisory, so these are worth reading and are not a rejection.
     * @type {Array<ComplianceViolationOut>}
     * @memberof RenderComplianceOut
     */
    advisories?: Array<ComplianceViolationOut>;
}

/**
 * Check if a given object implements the RenderComplianceOut interface.
 */
export function instanceOfRenderComplianceOut(value: object): value is RenderComplianceOut {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('rulesetVersion' in value) || value['rulesetVersion'] === undefined) return false;
    if (!('fullyChecked' in value) || value['fullyChecked'] === undefined) return false;
    return true;
}

export function RenderComplianceOutFromJSON(json: any): RenderComplianceOut {
    return RenderComplianceOutFromJSONTyped(json, false);
}

export function RenderComplianceOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderComplianceOut {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'],
        'rulesetVersion': json['ruleset_version'],
        'fullyChecked': json['fully_checked'],
        'advisories': json['advisories'] == null ? undefined : ((json['advisories'] as Array<any>).map(ComplianceViolationOutFromJSON)),
    };
}

export function RenderComplianceOutToJSON(value?: RenderComplianceOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'profile': value['profile'],
        'ruleset_version': value['rulesetVersion'],
        'fully_checked': value['fullyChecked'],
        'advisories': value['advisories'] == null ? undefined : ((value['advisories'] as Array<any>).map(ComplianceViolationOutToJSON)),
    };
}

