/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RenderComplianceOut } from './RenderComplianceOut';
import {
    RenderComplianceOutFromJSON,
    RenderComplianceOutFromJSONTyped,
    RenderComplianceOutToJSON,
} from './RenderComplianceOut';
import type { RenderStatus } from './RenderStatus';
import {
    RenderStatusFromJSON,
    RenderStatusFromJSONTyped,
    RenderStatusToJSON,
} from './RenderStatus';
import type { RenderFailureOut } from './RenderFailureOut';
import {
    RenderFailureOutFromJSON,
    RenderFailureOutFromJSONTyped,
    RenderFailureOutToJSON,
} from './RenderFailureOut';
import type { CalculationBreakdown } from './CalculationBreakdown';
import {
    CalculationBreakdownFromJSON,
    CalculationBreakdownFromJSONTyped,
    CalculationBreakdownToJSON,
} from './CalculationBreakdown';

/**
 * 
 * @export
 * @interface RenderOut
 */
export interface RenderOut {
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    id: string;
    /**
     * 
     * @type {RenderStatus}
     * @memberof RenderOut
     */
    status: RenderStatus;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    documentType: RenderOutDocumentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    templateId: string;
    /**
     * 
     * @type {number}
     * @memberof RenderOut
     */
    templateVersion?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    format: RenderOutFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    downloadUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    expiresAt?: string | null;
    /**
     * 
     * @type {CalculationBreakdown}
     * @memberof RenderOut
     */
    calculation: CalculationBreakdown;
    /**
     * 
     * @type {string}
     * @memberof RenderOut
     */
    createdAt: string;
    /**
     * 
     * @type {RenderComplianceOut}
     * @memberof RenderOut
     */
    compliance?: RenderComplianceOut | null;
    /**
     * 
     * @type {RenderFailureOut}
     * @memberof RenderOut
     */
    failure?: RenderFailureOut | null;
}


/**
 * @export
 */
export const RenderOutDocumentTypeEnum = {
    Invoice: 'invoice',
    CreditNote: 'credit_note',
    DebitNote: 'debit_note',
    Quote: 'quote',
    Receipt: 'receipt',
    Proforma: 'proforma',
    PurchaseOrder: 'purchase_order',
    DeliveryNote: 'delivery_note'
} as const;
export type RenderOutDocumentTypeEnum = typeof RenderOutDocumentTypeEnum[keyof typeof RenderOutDocumentTypeEnum];

/**
 * @export
 */
export const RenderOutFormatEnum = {
    Pdf: 'pdf'
} as const;
export type RenderOutFormatEnum = typeof RenderOutFormatEnum[keyof typeof RenderOutFormatEnum];


/**
 * Check if a given object implements the RenderOut interface.
 */
export function instanceOfRenderOut(value: object): value is RenderOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('documentType' in value) || value['documentType'] === undefined) return false;
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('calculation' in value) || value['calculation'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function RenderOutFromJSON(json: any): RenderOut {
    return RenderOutFromJSONTyped(json, false);
}

export function RenderOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenderOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': RenderStatusFromJSON(json['status']),
        'documentType': json['document_type'],
        'templateId': json['template_id'],
        'templateVersion': json['template_version'] == null ? undefined : json['template_version'],
        'format': json['format'],
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'calculation': CalculationBreakdownFromJSON(json['calculation']),
        'createdAt': json['created_at'],
        'compliance': json['compliance'] == null ? undefined : RenderComplianceOutFromJSON(json['compliance']),
        'failure': json['failure'] == null ? undefined : RenderFailureOutFromJSON(json['failure']),
    };
}

export function RenderOutToJSON(value?: RenderOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'status': RenderStatusToJSON(value['status']),
        'document_type': value['documentType'],
        'template_id': value['templateId'],
        'template_version': value['templateVersion'],
        'format': value['format'],
        'download_url': value['downloadUrl'],
        'expires_at': value['expiresAt'],
        'calculation': CalculationBreakdownToJSON(value['calculation']),
        'created_at': value['createdAt'],
        'compliance': RenderComplianceOutToJSON(value['compliance']),
        'failure': RenderFailureOutToJSON(value['failure']),
    };
}

