/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Generic boolean response envelope.
 * 
 * Example:
 * {"data": {"deleted": true}}
 * @export
 * @interface SimpleBoolResponse
 */
export interface SimpleBoolResponse {
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof SimpleBoolResponse
     */
    data: { [key: string]: boolean; };
}

/**
 * Check if a given object implements the SimpleBoolResponse interface.
 */
export function instanceOfSimpleBoolResponse(value: object): value is SimpleBoolResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SimpleBoolResponseFromJSON(json: any): SimpleBoolResponse {
    return SimpleBoolResponseFromJSONTyped(json, false);
}

export function SimpleBoolResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleBoolResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
    };
}

export function SimpleBoolResponseToJSON(value?: SimpleBoolResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'],
    };
}

