/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxRateOut
 */
export interface TaxRateOut {
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    rate: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaxRateOut
     */
    inclusive: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    jurisdiction?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TaxRateOut
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof TaxRateOut
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the TaxRateOut interface.
 */
export function instanceOfTaxRateOut(value: object): value is TaxRateOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    if (!('inclusive' in value) || value['inclusive'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function TaxRateOutFromJSON(json: any): TaxRateOut {
    return TaxRateOutFromJSONTyped(json, false);
}

export function TaxRateOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxRateOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'rate': json['rate'],
        'inclusive': json['inclusive'],
        'jurisdiction': json['jurisdiction'] == null ? undefined : json['jurisdiction'],
        'isActive': json['is_active'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function TaxRateOutToJSON(value?: TaxRateOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'rate': value['rate'],
        'inclusive': value['inclusive'],
        'jurisdiction': value['jurisdiction'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

