/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TaxRateOut } from './TaxRateOut';
import {
    TaxRateOutFromJSON,
    TaxRateOutFromJSONTyped,
    TaxRateOutToJSON,
} from './TaxRateOut';

/**
 * 
 * @export
 * @interface TaxRateResponse
 */
export interface TaxRateResponse {
    /**
     * 
     * @type {TaxRateOut}
     * @memberof TaxRateResponse
     */
    data: TaxRateOut;
}

/**
 * Check if a given object implements the TaxRateResponse interface.
 */
export function instanceOfTaxRateResponse(value: object): value is TaxRateResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TaxRateResponseFromJSON(json: any): TaxRateResponse {
    return TaxRateResponseFromJSONTyped(json, false);
}

export function TaxRateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxRateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TaxRateOutFromJSON(json['data']),
    };
}

export function TaxRateResponseToJSON(value?: TaxRateResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': TaxRateOutToJSON(value['data']),
    };
}

