/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaxRateCreateRequest
 */
export interface TaxRateCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof TaxRateCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TaxRateCreateRequest
     */
    rate: string;
    /**
     * 
     * @type {boolean}
     * @memberof TaxRateCreateRequest
     */
    inclusive?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TaxRateCreateRequest
     */
    jurisdiction?: string | null;
}

/**
 * Check if a given object implements the TaxRateCreateRequest interface.
 */
export function instanceOfTaxRateCreateRequest(value: object): value is TaxRateCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('rate' in value) || value['rate'] === undefined) return false;
    return true;
}

export function TaxRateCreateRequestFromJSON(json: any): TaxRateCreateRequest {
    return TaxRateCreateRequestFromJSONTyped(json, false);
}

export function TaxRateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaxRateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'rate': json['rate'],
        'inclusive': json['inclusive'] == null ? undefined : json['inclusive'],
        'jurisdiction': json['jurisdiction'] == null ? undefined : json['jurisdiction'],
    };
}

export function TaxRateCreateRequestToJSON(value?: TaxRateCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'rate': value['rate'],
        'inclusive': value['inclusive'],
        'jurisdiction': value['jurisdiction'],
    };
}

