/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateCreateRequest
 */
export interface TemplateCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplateCreateRequest
     */
    baseTemplateId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TemplateCreateRequest
     */
    config?: { [key: string]: any; };
}

/**
 * Check if a given object implements the TemplateCreateRequest interface.
 */
export function instanceOfTemplateCreateRequest(value: object): value is TemplateCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TemplateCreateRequestFromJSON(json: any): TemplateCreateRequest {
    return TemplateCreateRequestFromJSONTyped(json, false);
}

export function TemplateCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'baseTemplateId': json['base_template_id'] == null ? undefined : json['base_template_id'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function TemplateCreateRequestToJSON(value?: TemplateCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'base_template_id': value['baseTemplateId'],
        'config': value['config'],
    };
}

