/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TemplateVersionOut } from './TemplateVersionOut';
import {
    TemplateVersionOutFromJSON,
    TemplateVersionOutFromJSONTyped,
    TemplateVersionOutToJSON,
} from './TemplateVersionOut';

/**
 * 
 * @export
 * @interface TemplateVersionResponse
 */
export interface TemplateVersionResponse {
    /**
     * 
     * @type {TemplateVersionOut}
     * @memberof TemplateVersionResponse
     */
    data: TemplateVersionOut;
}

/**
 * Check if a given object implements the TemplateVersionResponse interface.
 */
export function instanceOfTemplateVersionResponse(value: object): value is TemplateVersionResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function TemplateVersionResponseFromJSON(json: any): TemplateVersionResponse {
    return TemplateVersionResponseFromJSONTyped(json, false);
}

export function TemplateVersionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateVersionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': TemplateVersionOutFromJSON(json['data']),
    };
}

export function TemplateVersionResponseToJSON(value?: TemplateVersionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': TemplateVersionOutToJSON(value['data']),
    };
}

