/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateDetail
 */
export interface TemplateDetail {
    /**
     * 
     * @type {string}
     * @memberof TemplateDetail
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateDetail
     */
    documentType?: TemplateDetailDocumentTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TemplateDetail
     */
    engine: string;
}


/**
 * @export
 */
export const TemplateDetailDocumentTypeEnum = {
    Invoice: 'invoice'
} as const;
export type TemplateDetailDocumentTypeEnum = typeof TemplateDetailDocumentTypeEnum[keyof typeof TemplateDetailDocumentTypeEnum];


/**
 * Check if a given object implements the TemplateDetail interface.
 */
export function instanceOfTemplateDetail(value: object): value is TemplateDetail {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('engine' in value) || value['engine'] === undefined) return false;
    return true;
}

export function TemplateDetailFromJSON(json: any): TemplateDetail {
    return TemplateDetailFromJSONTyped(json, false);
}

export function TemplateDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'],
        'name': json['name'],
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
        'engine': json['engine'],
    };
}

export function TemplateDetailToJSON(value?: TemplateDetail | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'template_id': value['templateId'],
        'name': value['name'],
        'document_type': value['documentType'],
        'engine': value['engine'],
    };
}

