/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateSummary
 */
export interface TemplateSummary {
    /**
     * 
     * @type {string}
     * @memberof TemplateSummary
     */
    templateId: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateSummary
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateSummary
     */
    documentType?: TemplateSummaryDocumentTypeEnum;
}


/**
 * @export
 */
export const TemplateSummaryDocumentTypeEnum = {
    Invoice: 'invoice'
} as const;
export type TemplateSummaryDocumentTypeEnum = typeof TemplateSummaryDocumentTypeEnum[keyof typeof TemplateSummaryDocumentTypeEnum];


/**
 * Check if a given object implements the TemplateSummary interface.
 */
export function instanceOfTemplateSummary(value: object): value is TemplateSummary {
    if (!('templateId' in value) || value['templateId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TemplateSummaryFromJSON(json: any): TemplateSummary {
    return TemplateSummaryFromJSONTyped(json, false);
}

export function TemplateSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'templateId': json['template_id'],
        'name': json['name'],
        'documentType': json['document_type'] == null ? undefined : json['document_type'],
    };
}

export function TemplateSummaryToJSON(value?: TemplateSummary | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'template_id': value['templateId'],
        'name': value['name'],
        'document_type': value['documentType'],
    };
}

