/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplatePatchRequest
 */
export interface TemplatePatchRequest {
    /**
     * 
     * @type {string}
     * @memberof TemplatePatchRequest
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TemplatePatchRequest
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof TemplatePatchRequest
     */
    config?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the TemplatePatchRequest interface.
 */
export function instanceOfTemplatePatchRequest(value: object): value is TemplatePatchRequest {
    return true;
}

export function TemplatePatchRequestFromJSON(json: any): TemplatePatchRequest {
    return TemplatePatchRequestFromJSONTyped(json, false);
}

export function TemplatePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplatePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'config': json['config'] == null ? undefined : json['config'],
    };
}

export function TemplatePatchRequestToJSON(value?: TemplatePatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'config': value['config'],
    };
}

