/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsageRenderLimits
 */
export interface UsageRenderLimits {
    /**
     * 
     * @type {number}
     * @memberof UsageRenderLimits
     */
    used: number;
    /**
     * 
     * @type {number}
     * @memberof UsageRenderLimits
     */
    limit: number;
    /**
     * 
     * @type {number}
     * @memberof UsageRenderLimits
     */
    remaining: number;
}

/**
 * Check if a given object implements the UsageRenderLimits interface.
 */
export function instanceOfUsageRenderLimits(value: object): value is UsageRenderLimits {
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('remaining' in value) || value['remaining'] === undefined) return false;
    return true;
}

export function UsageRenderLimitsFromJSON(json: any): UsageRenderLimits {
    return UsageRenderLimitsFromJSONTyped(json, false);
}

export function UsageRenderLimitsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageRenderLimits {
    if (json == null) {
        return json;
    }
    return {
        
        'used': json['used'],
        'limit': json['limit'],
        'remaining': json['remaining'],
    };
}

export function UsageRenderLimitsToJSON(value?: UsageRenderLimits | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'used': value['used'],
        'limit': value['limit'],
        'remaining': value['remaining'],
    };
}

