/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsagePeriod
 */
export interface UsagePeriod {
    /**
     * 
     * @type {string}
     * @memberof UsagePeriod
     */
    start: string;
    /**
     * 
     * @type {string}
     * @memberof UsagePeriod
     */
    end: string;
}

/**
 * Check if a given object implements the UsagePeriod interface.
 */
export function instanceOfUsagePeriod(value: object): value is UsagePeriod {
    if (!('start' in value) || value['start'] === undefined) return false;
    if (!('end' in value) || value['end'] === undefined) return false;
    return true;
}

export function UsagePeriodFromJSON(json: any): UsagePeriod {
    return UsagePeriodFromJSONTyped(json, false);
}

export function UsagePeriodFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsagePeriod {
    if (json == null) {
        return json;
    }
    return {
        
        'start': json['start'],
        'end': json['end'],
    };
}

export function UsagePeriodToJSON(value?: UsagePeriod | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'start': value['start'],
        'end': value['end'],
    };
}

