/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Renders past the quota this period, and what they cost.
 * @export
 * @interface UsageOverage
 */
export interface UsageOverage {
    /**
     * 
     * @type {boolean}
     * @memberof UsageOverage
     */
    enabled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UsageOverage
     */
    available?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UsageOverage
     */
    renders?: number;
    /**
     * 
     * @type {number}
     * @memberof UsageOverage
     */
    priceMillicents?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UsageOverage
     */
    estimatedCostCents?: number;
}

/**
 * Check if a given object implements the UsageOverage interface.
 */
export function instanceOfUsageOverage(value: object): value is UsageOverage {
    return true;
}

export function UsageOverageFromJSON(json: any): UsageOverage {
    return UsageOverageFromJSONTyped(json, false);
}

export function UsageOverageFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsageOverage {
    if (json == null) {
        return json;
    }
    return {
        
        'enabled': json['enabled'] == null ? undefined : json['enabled'],
        'available': json['available'] == null ? undefined : json['available'],
        'renders': json['renders'] == null ? undefined : json['renders'],
        'priceMillicents': json['price_millicents'] == null ? undefined : json['price_millicents'],
        'estimatedCostCents': json['estimated_cost_cents'] == null ? undefined : json['estimated_cost_cents'],
    };
}

export function UsageOverageToJSON(value?: UsageOverage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'enabled': value['enabled'],
        'available': value['available'],
        'renders': value['renders'],
        'price_millicents': value['priceMillicents'],
        'estimated_cost_cents': value['estimatedCostCents'],
    };
}

