/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDeliveryOut
 */
export interface WebhookDeliveryOut {
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    endpointId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    eventType: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    status: WebhookDeliveryOutStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryOut
     */
    httpStatus?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryOut
     */
    attempts: number;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    errorMessage?: string | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryOut
     */
    deliveredAt?: string | null;
}


/**
 * @export
 */
export const WebhookDeliveryOutStatusEnum = {
    Pending: 'pending',
    Delivered: 'delivered',
    Failed: 'failed'
} as const;
export type WebhookDeliveryOutStatusEnum = typeof WebhookDeliveryOutStatusEnum[keyof typeof WebhookDeliveryOutStatusEnum];


/**
 * Check if a given object implements the WebhookDeliveryOut interface.
 */
export function instanceOfWebhookDeliveryOut(value: object): value is WebhookDeliveryOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('endpointId' in value) || value['endpointId'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WebhookDeliveryOutFromJSON(json: any): WebhookDeliveryOut {
    return WebhookDeliveryOutFromJSONTyped(json, false);
}

export function WebhookDeliveryOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'endpointId': json['endpoint_id'],
        'eventId': json['event_id'],
        'eventType': json['event_type'],
        'status': json['status'],
        'httpStatus': json['http_status'] == null ? undefined : json['http_status'],
        'attempts': json['attempts'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
        'createdAt': json['created_at'],
        'deliveredAt': json['delivered_at'] == null ? undefined : json['delivered_at'],
    };
}

export function WebhookDeliveryOutToJSON(value?: WebhookDeliveryOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'endpoint_id': value['endpointId'],
        'event_id': value['eventId'],
        'event_type': value['eventType'],
        'status': value['status'],
        'http_status': value['httpStatus'],
        'attempts': value['attempts'],
        'error_message': value['errorMessage'],
        'created_at': value['createdAt'],
        'delivered_at': value['deliveredAt'],
    };
}

