/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointCreateRequest
 */
export interface WebhookEndpointCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointCreateRequest
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointCreateRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookEndpointCreateRequest
     */
    events: Array<string>;
}

/**
 * Check if a given object implements the WebhookEndpointCreateRequest interface.
 */
export function instanceOfWebhookEndpointCreateRequest(value: object): value is WebhookEndpointCreateRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    return true;
}

export function WebhookEndpointCreateRequestFromJSON(json: any): WebhookEndpointCreateRequest {
    return WebhookEndpointCreateRequestFromJSONTyped(json, false);
}

export function WebhookEndpointCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'events': json['events'],
    };
}

export function WebhookEndpointCreateRequestToJSON(value?: WebhookEndpointCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'description': value['description'],
        'events': value['events'],
    };
}

