/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpointOut } from './WebhookEndpointOut';
import {
    WebhookEndpointOutFromJSON,
    WebhookEndpointOutFromJSONTyped,
    WebhookEndpointOutToJSON,
} from './WebhookEndpointOut';

/**
 * 
 * @export
 * @interface WebhookEndpointResponse
 */
export interface WebhookEndpointResponse {
    /**
     * 
     * @type {WebhookEndpointOut}
     * @memberof WebhookEndpointResponse
     */
    data: WebhookEndpointOut;
}

/**
 * Check if a given object implements the WebhookEndpointResponse interface.
 */
export function instanceOfWebhookEndpointResponse(value: object): value is WebhookEndpointResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WebhookEndpointResponseFromJSON(json: any): WebhookEndpointResponse {
    return WebhookEndpointResponseFromJSONTyped(json, false);
}

export function WebhookEndpointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WebhookEndpointOutFromJSON(json['data']),
    };
}

export function WebhookEndpointResponseToJSON(value?: WebhookEndpointResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': WebhookEndpointOutToJSON(value['data']),
    };
}

