/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointOut
 */
export interface WebhookEndpointOut {
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointOut
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointOut
     */
    description?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookEndpointOut
     */
    events: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpointOut
     */
    isActive: boolean;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointOut
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointOut
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the WebhookEndpointOut interface.
 */
export function instanceOfWebhookEndpointOut(value: object): value is WebhookEndpointOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WebhookEndpointOutFromJSON(json: any): WebhookEndpointOut {
    return WebhookEndpointOutFromJSONTyped(json, false);
}

export function WebhookEndpointOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'events': json['events'],
        'isActive': json['is_active'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
    };
}

export function WebhookEndpointOutToJSON(value?: WebhookEndpointOut | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'url': value['url'],
        'description': value['description'],
        'events': value['events'],
        'is_active': value['isActive'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

