/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookDeliveryOut } from './WebhookDeliveryOut';
import {
    WebhookDeliveryOutFromJSON,
    WebhookDeliveryOutFromJSONTyped,
    WebhookDeliveryOutToJSON,
} from './WebhookDeliveryOut';

/**
 * 
 * @export
 * @interface WebhookDeliveryResponse
 */
export interface WebhookDeliveryResponse {
    /**
     * 
     * @type {WebhookDeliveryOut}
     * @memberof WebhookDeliveryResponse
     */
    data: WebhookDeliveryOut;
}

/**
 * Check if a given object implements the WebhookDeliveryResponse interface.
 */
export function instanceOfWebhookDeliveryResponse(value: object): value is WebhookDeliveryResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WebhookDeliveryResponseFromJSON(json: any): WebhookDeliveryResponse {
    return WebhookDeliveryResponseFromJSONTyped(json, false);
}

export function WebhookDeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WebhookDeliveryOutFromJSON(json['data']),
    };
}

export function WebhookDeliveryResponseToJSON(value?: WebhookDeliveryResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': WebhookDeliveryOutToJSON(value['data']),
    };
}

