/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookDeliveryOut } from './WebhookDeliveryOut';
import {
    WebhookDeliveryOutFromJSON,
    WebhookDeliveryOutFromJSONTyped,
    WebhookDeliveryOutToJSON,
} from './WebhookDeliveryOut';
import type { CursorPagination } from './CursorPagination';
import {
    CursorPaginationFromJSON,
    CursorPaginationFromJSONTyped,
    CursorPaginationToJSON,
} from './CursorPagination';

/**
 * 
 * @export
 * @interface WebhookDeliveriesListResponse
 */
export interface WebhookDeliveriesListResponse {
    /**
     * 
     * @type {Array<WebhookDeliveryOut>}
     * @memberof WebhookDeliveriesListResponse
     */
    data: Array<WebhookDeliveryOut>;
    /**
     * 
     * @type {CursorPagination}
     * @memberof WebhookDeliveriesListResponse
     */
    pagination?: CursorPagination;
}

/**
 * Check if a given object implements the WebhookDeliveriesListResponse interface.
 */
export function instanceOfWebhookDeliveriesListResponse(value: object): value is WebhookDeliveriesListResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WebhookDeliveriesListResponseFromJSON(json: any): WebhookDeliveriesListResponse {
    return WebhookDeliveriesListResponseFromJSONTyped(json, false);
}

export function WebhookDeliveriesListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveriesListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(WebhookDeliveryOutFromJSON)),
        'pagination': json['pagination'] == null ? undefined : CursorPaginationFromJSON(json['pagination']),
    };
}

export function WebhookDeliveriesListResponseToJSON(value?: WebhookDeliveriesListResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(WebhookDeliveryOutToJSON)),
        'pagination': CursorPaginationToJSON(value['pagination']),
    };
}

