/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspacePatchRequest
 */
export interface WorkspacePatchRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkspacePatchRequest
     */
    name?: string | null;
}

/**
 * Check if a given object implements the WorkspacePatchRequest interface.
 */
export function instanceOfWorkspacePatchRequest(value: object): value is WorkspacePatchRequest {
    return true;
}

export function WorkspacePatchRequestFromJSON(json: any): WorkspacePatchRequest {
    return WorkspacePatchRequestFromJSONTyped(json, false);
}

export function WorkspacePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspacePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function WorkspacePatchRequestToJSON(value?: WorkspacePatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

