/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkspaceOut } from './WorkspaceOut';
import {
    WorkspaceOutFromJSON,
    WorkspaceOutFromJSONTyped,
    WorkspaceOutToJSON,
} from './WorkspaceOut';

/**
 * 
 * @export
 * @interface WorkspaceResponse
 */
export interface WorkspaceResponse {
    /**
     * 
     * @type {WorkspaceOut}
     * @memberof WorkspaceResponse
     */
    data: WorkspaceOut;
}

/**
 * Check if a given object implements the WorkspaceResponse interface.
 */
export function instanceOfWorkspaceResponse(value: object): value is WorkspaceResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function WorkspaceResponseFromJSON(json: any): WorkspaceResponse {
    return WorkspaceResponseFromJSONTyped(json, false);
}

export function WorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': WorkspaceOutFromJSON(json['data']),
    };
}

export function WorkspaceResponseToJSON(value?: WorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': WorkspaceOutToJSON(value['data']),
    };
}

