/* tslint:disable */
/* eslint-disable */
/**
 * InvoicePDFs
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkspaceCreateRequest
 */
export interface WorkspaceCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkspaceCreateRequest
     */
    name: string;
}

/**
 * Check if a given object implements the WorkspaceCreateRequest interface.
 */
export function instanceOfWorkspaceCreateRequest(value: object): value is WorkspaceCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function WorkspaceCreateRequestFromJSON(json: any): WorkspaceCreateRequest {
    return WorkspaceCreateRequestFromJSONTyped(json, false);
}

export function WorkspaceCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkspaceCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function WorkspaceCreateRequestToJSON(value?: WorkspaceCreateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

